sudo: enabled

os:
  - linux

before_script:
  - chmod +x ./linux/*.sh

script:
  - docker build -t $DOCKER_ID_USER/seppo:$TRAVIS_BRANCH-$TRAVIS_COMMIT .
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - docker push $DOCKER_ID_USER/seppo
  - ./linux/install_dependencies.sh
  - ./linux/setup_kubectl.sh
  - ./linux/install_tiller.sh
  - ./linux/helm_upgrade.sh