language: go
services:
  - docker
go:
  1.8.3
install:
  make install
script:
  - make build

after_success:
  - docker login -u $DOCKER_ID_USER -p $DOCKER_USER_PASSWORD
  - export REPO=$DOCKER_ID_USER/seppo
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

notifications:
  webhooks: http://salainen_kontti_updater.ths.tunk.org/