apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seppo
  labels:
    app: seppo
spec:
  template:
    metadata:
      labels:
      app: seppo
    spec:
      containers:
        - name: seppo-container
          image: jaska/seppo
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_USERNAME
              value: "asd"
            - name: MYSQL_PASSWORD
              value: "asd"
            - name: MYSQL_HOST
              value: "asd"
            - name: MYSQL_DATABASE
              value: "asd"
            - name: MATIAS_PORT
              value: "3343"
            - name: SEPPO_PORT
              value: "80"