// Code generated by protoc-gen-go.
// source: ew_database.proto
// DO NOT EDIT!

/*
Package SeppoService is a generated protocol buffer package.

It is generated from these files:
	ew_database.proto
	ew_song.proto
	ew_verse.proto
	seppo_service.proto
	song.proto
	song_database.proto
	song_database_variation.proto
	variation.proto

It has these top-level messages:
	EwDatabase
	EwDatabasesConnection
	ListenForChangedEwSongRequest
	FetchEwDatabasesRequest
	FetchEwDatabasesResponse
	FetchEwDatabaseByIdRequest
	FetchEwDatabaseByIdResponse
	CreateEwDatabaseRequest
	CreateEwDatabaseResponse
	RemoveEwDatabaseRequest
	RemoveEwDatabaseResponse
	SyncEwDatabaseRequest
	SyncEwDatabaseResponse
	EwSong
	EwVerse
	Song
	SongDatabase
	SongDatabaseEdge
	SongDatabasesConnection
	FetchSongDatabasesRequest
	FetchSongDatabaseByIdRequest
	FetchSongDatabaseByIdResponse
	CreateSongDatabaseRequest
	CreateSongDatabaseResponse
	EditSongDatabaseRequest
	EditSongDatabaseResponse
	RemoveSongDatabaseRequest
	RemoveSongDatabaseResponse
	SongDatabaseVariation
	SongDatabaseVariations
	FetchVariationsBySongDatabaseIdRequest
	FetchVariationsBySongDatabaseIdResponse
	AddVariationToSongDatabaseRequest
	AddVariationToSongDatabaseResponse
	RemoveVariationFromSongDatabaseRequest
	RemoveVariationFromSongDatabaseResponse
	Variation
	CreateVariationRequest
	CreateVariationResponse
	EditVariationRequest
	EditVariationResponse
	RemoveVariationRequest
	RemoveVariationResponse
	FetchVariationByIdRequest
	FetchVariationByIdResponse
	SearchVariationsRequest
	SearchVariationsResponse
*/
package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EwDatabase struct {
	Id             uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SongDatabaseId uint32 `protobuf:"varint,3,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
	Version        uint64 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
}

func (m *EwDatabase) Reset()                    { *m = EwDatabase{} }
func (m *EwDatabase) String() string            { return proto.CompactTextString(m) }
func (*EwDatabase) ProtoMessage()               {}
func (*EwDatabase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EwDatabase) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EwDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EwDatabase) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

func (m *EwDatabase) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type EwDatabasesConnection struct {
	EwDatabases []*EwDatabase `protobuf:"bytes,1,rep,name=ewDatabases" json:"ewDatabases,omitempty"`
}

func (m *EwDatabasesConnection) Reset()                    { *m = EwDatabasesConnection{} }
func (m *EwDatabasesConnection) String() string            { return proto.CompactTextString(m) }
func (*EwDatabasesConnection) ProtoMessage()               {}
func (*EwDatabasesConnection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EwDatabasesConnection) GetEwDatabases() []*EwDatabase {
	if m != nil {
		return m.EwDatabases
	}
	return nil
}

type ListenForChangedEwSongRequest struct {
	EwDatabaseId uint32 `protobuf:"varint,1,opt,name=ewDatabaseId" json:"ewDatabaseId,omitempty"`
}

func (m *ListenForChangedEwSongRequest) Reset()                    { *m = ListenForChangedEwSongRequest{} }
func (m *ListenForChangedEwSongRequest) String() string            { return proto.CompactTextString(m) }
func (*ListenForChangedEwSongRequest) ProtoMessage()               {}
func (*ListenForChangedEwSongRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListenForChangedEwSongRequest) GetEwDatabaseId() uint32 {
	if m != nil {
		return m.EwDatabaseId
	}
	return 0
}

type FetchEwDatabasesRequest struct {
}

func (m *FetchEwDatabasesRequest) Reset()                    { *m = FetchEwDatabasesRequest{} }
func (m *FetchEwDatabasesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchEwDatabasesRequest) ProtoMessage()               {}
func (*FetchEwDatabasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type FetchEwDatabasesResponse struct {
	EwDatabases []*EwDatabase `protobuf:"bytes,1,rep,name=ewDatabases" json:"ewDatabases,omitempty"`
}

func (m *FetchEwDatabasesResponse) Reset()                    { *m = FetchEwDatabasesResponse{} }
func (m *FetchEwDatabasesResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchEwDatabasesResponse) ProtoMessage()               {}
func (*FetchEwDatabasesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FetchEwDatabasesResponse) GetEwDatabases() []*EwDatabase {
	if m != nil {
		return m.EwDatabases
	}
	return nil
}

type FetchEwDatabaseByIdRequest struct {
	EwDatabaseIds []uint32 `protobuf:"varint,1,rep,packed,name=ewDatabaseIds" json:"ewDatabaseIds,omitempty"`
}

func (m *FetchEwDatabaseByIdRequest) Reset()                    { *m = FetchEwDatabaseByIdRequest{} }
func (m *FetchEwDatabaseByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchEwDatabaseByIdRequest) ProtoMessage()               {}
func (*FetchEwDatabaseByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FetchEwDatabaseByIdRequest) GetEwDatabaseIds() []uint32 {
	if m != nil {
		return m.EwDatabaseIds
	}
	return nil
}

type FetchEwDatabaseByIdResponse struct {
	EwDatabases []*EwDatabase `protobuf:"bytes,1,rep,name=ewDatabases" json:"ewDatabases,omitempty"`
}

func (m *FetchEwDatabaseByIdResponse) Reset()                    { *m = FetchEwDatabaseByIdResponse{} }
func (m *FetchEwDatabaseByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchEwDatabaseByIdResponse) ProtoMessage()               {}
func (*FetchEwDatabaseByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FetchEwDatabaseByIdResponse) GetEwDatabases() []*EwDatabase {
	if m != nil {
		return m.EwDatabases
	}
	return nil
}

type CreateEwDatabaseRequest struct {
	SongDatabaseId uint32 `protobuf:"varint,1,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *CreateEwDatabaseRequest) Reset()                    { *m = CreateEwDatabaseRequest{} }
func (m *CreateEwDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEwDatabaseRequest) ProtoMessage()               {}
func (*CreateEwDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateEwDatabaseRequest) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

func (m *CreateEwDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateEwDatabaseResponse struct {
	EwDatabase *EwDatabase `protobuf:"bytes,1,opt,name=ewDatabase" json:"ewDatabase,omitempty"`
}

func (m *CreateEwDatabaseResponse) Reset()                    { *m = CreateEwDatabaseResponse{} }
func (m *CreateEwDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateEwDatabaseResponse) ProtoMessage()               {}
func (*CreateEwDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateEwDatabaseResponse) GetEwDatabase() *EwDatabase {
	if m != nil {
		return m.EwDatabase
	}
	return nil
}

type RemoveEwDatabaseRequest struct {
	EwDatabaseId uint32 `protobuf:"varint,1,opt,name=ewDatabaseId" json:"ewDatabaseId,omitempty"`
}

func (m *RemoveEwDatabaseRequest) Reset()                    { *m = RemoveEwDatabaseRequest{} }
func (m *RemoveEwDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveEwDatabaseRequest) ProtoMessage()               {}
func (*RemoveEwDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RemoveEwDatabaseRequest) GetEwDatabaseId() uint32 {
	if m != nil {
		return m.EwDatabaseId
	}
	return 0
}

type RemoveEwDatabaseResponse struct {
}

func (m *RemoveEwDatabaseResponse) Reset()                    { *m = RemoveEwDatabaseResponse{} }
func (m *RemoveEwDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveEwDatabaseResponse) ProtoMessage()               {}
func (*RemoveEwDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SyncEwDatabaseRequest struct {
	EwDatabaseId uint32    `protobuf:"varint,1,opt,name=EwDatabaseId" json:"EwDatabaseId,omitempty"`
	EwSongs      []*EwSong `protobuf:"bytes,2,rep,name=ewSongs" json:"ewSongs,omitempty"`
}

func (m *SyncEwDatabaseRequest) Reset()                    { *m = SyncEwDatabaseRequest{} }
func (m *SyncEwDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncEwDatabaseRequest) ProtoMessage()               {}
func (*SyncEwDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SyncEwDatabaseRequest) GetEwDatabaseId() uint32 {
	if m != nil {
		return m.EwDatabaseId
	}
	return 0
}

func (m *SyncEwDatabaseRequest) GetEwSongs() []*EwSong {
	if m != nil {
		return m.EwSongs
	}
	return nil
}

type SyncEwDatabaseResponse struct {
	EwSongs []*EwSong `protobuf:"bytes,1,rep,name=ewSongs" json:"ewSongs,omitempty"`
}

func (m *SyncEwDatabaseResponse) Reset()                    { *m = SyncEwDatabaseResponse{} }
func (m *SyncEwDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncEwDatabaseResponse) ProtoMessage()               {}
func (*SyncEwDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SyncEwDatabaseResponse) GetEwSongs() []*EwSong {
	if m != nil {
		return m.EwSongs
	}
	return nil
}

func init() {
	proto.RegisterType((*EwDatabase)(nil), "SeppoService.EwDatabase")
	proto.RegisterType((*EwDatabasesConnection)(nil), "SeppoService.EwDatabasesConnection")
	proto.RegisterType((*ListenForChangedEwSongRequest)(nil), "SeppoService.ListenForChangedEwSongRequest")
	proto.RegisterType((*FetchEwDatabasesRequest)(nil), "SeppoService.FetchEwDatabasesRequest")
	proto.RegisterType((*FetchEwDatabasesResponse)(nil), "SeppoService.FetchEwDatabasesResponse")
	proto.RegisterType((*FetchEwDatabaseByIdRequest)(nil), "SeppoService.FetchEwDatabaseByIdRequest")
	proto.RegisterType((*FetchEwDatabaseByIdResponse)(nil), "SeppoService.FetchEwDatabaseByIdResponse")
	proto.RegisterType((*CreateEwDatabaseRequest)(nil), "SeppoService.CreateEwDatabaseRequest")
	proto.RegisterType((*CreateEwDatabaseResponse)(nil), "SeppoService.CreateEwDatabaseResponse")
	proto.RegisterType((*RemoveEwDatabaseRequest)(nil), "SeppoService.RemoveEwDatabaseRequest")
	proto.RegisterType((*RemoveEwDatabaseResponse)(nil), "SeppoService.RemoveEwDatabaseResponse")
	proto.RegisterType((*SyncEwDatabaseRequest)(nil), "SeppoService.SyncEwDatabaseRequest")
	proto.RegisterType((*SyncEwDatabaseResponse)(nil), "SeppoService.SyncEwDatabaseResponse")
}

func init() { proto.RegisterFile("ew_database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6b, 0xa3, 0x40,
	0x18, 0xc5, 0xd1, 0x84, 0x0d, 0xfb, 0x25, 0x06, 0x76, 0xd8, 0x6c, 0x66, 0xb3, 0x2c, 0xc8, 0x50,
	0x8a, 0x27, 0x0f, 0xed, 0xa5, 0x14, 0x7a, 0x89, 0x4d, 0x68, 0xa0, 0x27, 0x6d, 0x0b, 0x3d, 0x05,
	0xa3, 0x1f, 0x89, 0x94, 0xcc, 0x58, 0xc7, 0x46, 0xf2, 0xdf, 0x97, 0x1a, 0xc5, 0x89, 0x4a, 0x09,
	0xb4, 0x37, 0xfd, 0xe6, 0xbd, 0x37, 0xbf, 0x19, 0x9f, 0xf0, 0x0b, 0xb3, 0x65, 0xe8, 0xa7, 0xfe,
	0xca, 0x97, 0x68, 0xc7, 0x89, 0x48, 0x05, 0x19, 0x78, 0x18, 0xc7, 0xc2, 0xc3, 0x64, 0x17, 0x05,
	0x38, 0x31, 0x30, 0x5b, 0x4a, 0xc1, 0xd7, 0x87, 0x45, 0x96, 0x00, 0xcc, 0xb2, 0xdb, 0xc2, 0x40,
	0x86, 0xa0, 0x47, 0x21, 0xd5, 0x4c, 0xcd, 0x32, 0x5c, 0x3d, 0x0a, 0x09, 0x81, 0x2e, 0xf7, 0xb7,
	0x48, 0x75, 0x53, 0xb3, 0x7e, 0xba, 0xf9, 0x33, 0x39, 0x87, 0xe1, 0x87, 0xbf, 0xf4, 0x2c, 0x42,
	0xda, 0xc9, 0xf5, 0xb5, 0x29, 0xa1, 0xd0, 0xdb, 0x61, 0x22, 0x23, 0xc1, 0x69, 0xd7, 0xd4, 0xac,
	0xae, 0x5b, 0xbe, 0x32, 0x0f, 0x46, 0xd5, 0x9e, 0xd2, 0x11, 0x9c, 0x63, 0x90, 0x46, 0x82, 0x93,
	0x6b, 0xe8, 0x63, 0xb5, 0x40, 0x35, 0xb3, 0x63, 0xf5, 0x2f, 0xa8, 0xad, 0xf2, 0xdb, 0x95, 0xd3,
	0x55, 0xc5, 0xcc, 0x81, 0xff, 0xf7, 0x91, 0x4c, 0x91, 0xcf, 0x45, 0xe2, 0x6c, 0x7c, 0xbe, 0xc6,
	0x70, 0x96, 0x79, 0x82, 0xaf, 0x5d, 0x7c, 0x7d, 0x43, 0x99, 0x12, 0x06, 0x83, 0x4a, 0xbf, 0x28,
	0x4f, 0x79, 0x34, 0x63, 0x7f, 0x61, 0x3c, 0xc7, 0x34, 0xd8, 0x28, 0x78, 0x85, 0x9d, 0x3d, 0x01,
	0x6d, 0x2e, 0xc9, 0x58, 0x70, 0x89, 0x5f, 0xe2, 0x9e, 0xc2, 0xa4, 0x96, 0x3b, 0xdd, 0x2f, 0xc2,
	0x12, 0xfa, 0x0c, 0x0c, 0x15, 0xf0, 0x90, 0x6d, 0xb8, 0xc7, 0x43, 0xf6, 0x0c, 0xff, 0x5a, 0x33,
	0xbe, 0x01, 0xef, 0x11, 0xc6, 0x4e, 0x82, 0x7e, 0x8a, 0x8a, 0xa0, 0x60, 0x6b, 0x16, 0x41, 0x6b,
	0x2d, 0x42, 0x4b, 0x89, 0xd8, 0x03, 0xd0, 0x66, 0x6c, 0x81, 0x7b, 0x05, 0x50, 0x11, 0xe4, 0x99,
	0x9f, 0xd1, 0x2a, 0x5a, 0x76, 0x03, 0x63, 0x17, 0xb7, 0x62, 0xd7, 0x02, 0x7b, 0xca, 0xd7, 0x9f,
	0x00, 0x6d, 0xda, 0x0f, 0x50, 0xec, 0x05, 0x46, 0xde, 0x9e, 0x07, 0xad, 0xc1, 0xb3, 0x96, 0x60,
	0x75, 0x46, 0x6c, 0xe8, 0x61, 0xde, 0x45, 0x49, 0xf5, 0xfc, 0xf2, 0x7f, 0xd7, 0x8f, 0x93, 0x17,
	0xb5, 0x14, 0xb1, 0x3b, 0xf8, 0x53, 0xdf, 0xac, 0xb8, 0x1b, 0x25, 0x49, 0x3b, 0x21, 0x69, 0xf5,
	0x23, 0xff, 0xcb, 0x2f, 0xdf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xff, 0xbc, 0x49, 0x87, 0x17, 0x04,
	0x00, 0x00,
}
