// Code generated by protoc-gen-go.
// source: language.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Language struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Language) Reset()                    { *m = Language{} }
func (m *Language) String() string            { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()               {}
func (*Language) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Language) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LanguagesConnection struct {
	Languages    []*Language `protobuf:"bytes,1,rep,name=languages" json:"languages,omitempty"`
	MaxLanguages uint32      `protobuf:"varint,2,opt,name=maxLanguages" json:"maxLanguages,omitempty"`
}

func (m *LanguagesConnection) Reset()                    { *m = LanguagesConnection{} }
func (m *LanguagesConnection) String() string            { return proto.CompactTextString(m) }
func (*LanguagesConnection) ProtoMessage()               {}
func (*LanguagesConnection) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *LanguagesConnection) GetLanguages() []*Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *LanguagesConnection) GetMaxLanguages() uint32 {
	if m != nil {
		return m.MaxLanguages
	}
	return 0
}

type SearchLanguagesRequest struct {
}

func (m *SearchLanguagesRequest) Reset()                    { *m = SearchLanguagesRequest{} }
func (m *SearchLanguagesRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchLanguagesRequest) ProtoMessage()               {}
func (*SearchLanguagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

type FetchLanguageByIdRequest struct {
	LanguagesIds []uint32 `protobuf:"varint,1,rep,packed,name=languagesIds" json:"languagesIds,omitempty"`
}

func (m *FetchLanguageByIdRequest) Reset()                    { *m = FetchLanguageByIdRequest{} }
func (m *FetchLanguageByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchLanguageByIdRequest) ProtoMessage()               {}
func (*FetchLanguageByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{3} }

func (m *FetchLanguageByIdRequest) GetLanguagesIds() []uint32 {
	if m != nil {
		return m.LanguagesIds
	}
	return nil
}

type FetchLanguageByIdResponse struct {
	Languages []*Language `protobuf:"bytes,1,rep,name=languages" json:"languages,omitempty"`
}

func (m *FetchLanguageByIdResponse) Reset()                    { *m = FetchLanguageByIdResponse{} }
func (m *FetchLanguageByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchLanguageByIdResponse) ProtoMessage()               {}
func (*FetchLanguageByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{4} }

func (m *FetchLanguageByIdResponse) GetLanguages() []*Language {
	if m != nil {
		return m.Languages
	}
	return nil
}

type CreateLanguageRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateLanguageRequest) Reset()                    { *m = CreateLanguageRequest{} }
func (m *CreateLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateLanguageRequest) ProtoMessage()               {}
func (*CreateLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{5} }

func (m *CreateLanguageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateLanguageResponse struct {
	Language *Language `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
}

func (m *CreateLanguageResponse) Reset()                    { *m = CreateLanguageResponse{} }
func (m *CreateLanguageResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateLanguageResponse) ProtoMessage()               {}
func (*CreateLanguageResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{6} }

func (m *CreateLanguageResponse) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

type EditLanguageRequest struct {
	LanguageId uint32 `protobuf:"varint,1,opt,name=languageId" json:"languageId,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EditLanguageRequest) Reset()                    { *m = EditLanguageRequest{} }
func (m *EditLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*EditLanguageRequest) ProtoMessage()               {}
func (*EditLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{7} }

func (m *EditLanguageRequest) GetLanguageId() uint32 {
	if m != nil {
		return m.LanguageId
	}
	return 0
}

func (m *EditLanguageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EditLanguageResponse struct {
	Language *Language `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
}

func (m *EditLanguageResponse) Reset()                    { *m = EditLanguageResponse{} }
func (m *EditLanguageResponse) String() string            { return proto.CompactTextString(m) }
func (*EditLanguageResponse) ProtoMessage()               {}
func (*EditLanguageResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{8} }

func (m *EditLanguageResponse) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

type RemoveLanguageRequest struct {
	LanguageId uint32 `protobuf:"varint,1,opt,name=languageId" json:"languageId,omitempty"`
}

func (m *RemoveLanguageRequest) Reset()                    { *m = RemoveLanguageRequest{} }
func (m *RemoveLanguageRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveLanguageRequest) ProtoMessage()               {}
func (*RemoveLanguageRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{9} }

func (m *RemoveLanguageRequest) GetLanguageId() uint32 {
	if m != nil {
		return m.LanguageId
	}
	return 0
}

type RemoveLanguageResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RemoveLanguageResponse) Reset()                    { *m = RemoveLanguageResponse{} }
func (m *RemoveLanguageResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveLanguageResponse) ProtoMessage()               {}
func (*RemoveLanguageResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{10} }

func (m *RemoveLanguageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Language)(nil), "SeppoService.Language")
	proto.RegisterType((*LanguagesConnection)(nil), "SeppoService.LanguagesConnection")
	proto.RegisterType((*SearchLanguagesRequest)(nil), "SeppoService.SearchLanguagesRequest")
	proto.RegisterType((*FetchLanguageByIdRequest)(nil), "SeppoService.FetchLanguageByIdRequest")
	proto.RegisterType((*FetchLanguageByIdResponse)(nil), "SeppoService.FetchLanguageByIdResponse")
	proto.RegisterType((*CreateLanguageRequest)(nil), "SeppoService.CreateLanguageRequest")
	proto.RegisterType((*CreateLanguageResponse)(nil), "SeppoService.CreateLanguageResponse")
	proto.RegisterType((*EditLanguageRequest)(nil), "SeppoService.EditLanguageRequest")
	proto.RegisterType((*EditLanguageResponse)(nil), "SeppoService.EditLanguageResponse")
	proto.RegisterType((*RemoveLanguageRequest)(nil), "SeppoService.RemoveLanguageRequest")
	proto.RegisterType((*RemoveLanguageResponse)(nil), "SeppoService.RemoveLanguageResponse")
}

func init() { proto.RegisterFile("language.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4f, 0x4f, 0xb3, 0x30,
	0x18, 0x0f, 0x7b, 0xdf, 0xe8, 0xf6, 0x38, 0x76, 0xe8, 0x1c, 0xa9, 0x17, 0x43, 0x7a, 0x22, 0x31,
	0xe1, 0x80, 0x26, 0xde, 0x3c, 0xb8, 0x68, 0x82, 0xd9, 0xc5, 0xf2, 0x09, 0x2a, 0x3c, 0x99, 0x24,
	0xd2, 0x22, 0x2d, 0x8b, 0x7e, 0x7b, 0x23, 0x52, 0x06, 0x64, 0x1e, 0xd4, 0x1b, 0xfc, 0xfe, 0xd3,
	0x02, 0x8b, 0x17, 0x21, 0xb7, 0xb5, 0xd8, 0x62, 0x58, 0x56, 0xca, 0x28, 0x32, 0x4f, 0xb0, 0x2c,
	0x55, 0x82, 0xd5, 0x2e, 0x4f, 0x91, 0x85, 0x30, 0xdd, 0xb4, 0x3c, 0x59, 0xc0, 0x24, 0xcf, 0xa8,
	0xe3, 0x3b, 0x81, 0xcb, 0x27, 0x79, 0x46, 0x08, 0xfc, 0x97, 0xa2, 0x40, 0x3a, 0xf1, 0x9d, 0x60,
	0xc6, 0x9b, 0x67, 0xa6, 0x60, 0x69, 0xf5, 0x7a, 0xad, 0xa4, 0xc4, 0xd4, 0xe4, 0x4a, 0x92, 0x2b,
	0x98, 0xd9, 0x1a, 0x4d, 0x1d, 0xff, 0x5f, 0x70, 0x12, 0x79, 0x61, 0xbf, 0x28, 0xb4, 0x2e, 0xbe,
	0x17, 0x12, 0x06, 0xf3, 0x42, 0xbc, 0x75, 0x79, 0x4d, 0x91, 0xcb, 0x07, 0x18, 0xa3, 0xe0, 0x25,
	0x28, 0xaa, 0xf4, 0xb9, 0x83, 0x38, 0xbe, 0xd6, 0xa8, 0x0d, 0xbb, 0x01, 0x7a, 0x8f, 0x66, 0x4f,
	0xdc, 0xbe, 0xc7, 0x59, 0xcb, 0x7d, 0x26, 0x77, 0x35, 0x71, 0xf6, 0x35, 0xc9, 0xe5, 0x03, 0x8c,
	0x3d, 0xc2, 0xd9, 0x01, 0xbf, 0x2e, 0x95, 0xd4, 0xf8, 0xbb, 0x0f, 0x62, 0x17, 0xb0, 0x5a, 0x57,
	0x28, 0x0c, 0x76, 0x64, 0xbb, 0xc7, 0x1e, 0xa5, 0xd3, 0x3b, 0xca, 0x0d, 0x78, 0x63, 0x71, 0x5b,
	0x1e, 0xc1, 0xd4, 0x66, 0x36, 0x8e, 0xef, 0xbb, 0x3b, 0x1d, 0x8b, 0x61, 0x79, 0x97, 0xe5, 0x66,
	0x5c, 0x7c, 0x0e, 0x60, 0x25, 0xb1, 0xbd, 0xdb, 0x1e, 0x72, 0xf0, 0x8e, 0x1f, 0xe0, 0x74, 0x18,
	0xf5, 0x87, 0x59, 0xd7, 0xb0, 0xe2, 0x58, 0xa8, 0x1d, 0xfe, 0x70, 0x18, 0x8b, 0xc0, 0x1b, 0x1b,
	0xdb, 0x19, 0x14, 0x8e, 0x75, 0x9d, 0xa6, 0xa8, 0x75, 0x63, 0x9b, 0x72, 0xfb, 0xfa, 0x74, 0xd4,
	0xfc, 0xe1, 0x97, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xde, 0x25, 0xe1, 0x33, 0xf3, 0x02, 0x00,
	0x00,
}
