// Code generated by protoc-gen-go.
// source: log.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Log struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	LogType     uint32 `protobuf:"varint,2,opt,name=logType" json:"logType,omitempty"`
	Message     string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	MessageDate int64  `protobuf:"varint,4,opt,name=messageDate" json:"messageDate,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Log) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Log) GetLogType() uint32 {
	if m != nil {
		return m.LogType
	}
	return 0
}

func (m *Log) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Log) GetMessageDate() int64 {
	if m != nil {
		return m.MessageDate
	}
	return 0
}

type SearchLogsRequest struct {
	Offset      uint32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit       uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	MessageType uint32 `protobuf:"varint,3,opt,name=messageType" json:"messageType,omitempty"`
	StartDate   int64  `protobuf:"varint,4,opt,name=startDate" json:"startDate,omitempty"`
	EndDate     int64  `protobuf:"varint,5,opt,name=endDate" json:"endDate,omitempty"`
	SearchWord  string `protobuf:"bytes,6,opt,name=searchWord" json:"searchWord,omitempty"`
}

func (m *SearchLogsRequest) Reset()                    { *m = SearchLogsRequest{} }
func (m *SearchLogsRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchLogsRequest) ProtoMessage()               {}
func (*SearchLogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SearchLogsRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchLogsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchLogsRequest) GetMessageType() uint32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *SearchLogsRequest) GetStartDate() int64 {
	if m != nil {
		return m.StartDate
	}
	return 0
}

func (m *SearchLogsRequest) GetEndDate() int64 {
	if m != nil {
		return m.EndDate
	}
	return 0
}

func (m *SearchLogsRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

type SearchLogsResponse struct {
	Logs    []*Log `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	MaxLogs uint64 `protobuf:"varint,2,opt,name=maxLogs" json:"maxLogs,omitempty"`
}

func (m *SearchLogsResponse) Reset()                    { *m = SearchLogsResponse{} }
func (m *SearchLogsResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchLogsResponse) ProtoMessage()               {}
func (*SearchLogsResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *SearchLogsResponse) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *SearchLogsResponse) GetMaxLogs() uint64 {
	if m != nil {
		return m.MaxLogs
	}
	return 0
}

func init() {
	proto.RegisterType((*Log)(nil), "SeppoService.Log")
	proto.RegisterType((*SearchLogsRequest)(nil), "SeppoService.SearchLogsRequest")
	proto.RegisterType((*SearchLogsResponse)(nil), "SeppoService.SearchLogsResponse")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xc9, 0xb6, 0x5b, 0xe9, 0xac, 0x2b, 0x6c, 0x10, 0xc9, 0x41, 0x24, 0x14, 0x84, 0x9e,
	0x7a, 0xd0, 0x57, 0xf0, 0xd8, 0x53, 0xaa, 0x78, 0xae, 0xdb, 0xd9, 0x58, 0xec, 0xee, 0xd4, 0x24,
	0x8a, 0x3e, 0x9b, 0x2f, 0x27, 0x1d, 0x5b, 0xcc, 0xad, 0xdf, 0xff, 0x53, 0xe6, 0x9b, 0x09, 0xe4,
	0x03, 0xd9, 0x6a, 0x74, 0x14, 0x48, 0x9e, 0x37, 0x38, 0x8e, 0xd4, 0xa0, 0xfb, 0xec, 0xf7, 0x58,
	0xbc, 0x41, 0x52, 0x93, 0x95, 0x17, 0xb0, 0xea, 0x3b, 0x25, 0xb4, 0x28, 0x53, 0xb3, 0xea, 0x3b,
	0xa9, 0xe0, 0x6c, 0x20, 0xfb, 0xf8, 0x3d, 0xa2, 0x5a, 0x69, 0x51, 0x6e, 0xcd, 0x82, 0x53, 0x73,
	0x44, 0xef, 0x5b, 0x8b, 0x2a, 0xd1, 0xa2, 0xcc, 0xcd, 0x82, 0x52, 0xc3, 0x66, 0xfe, 0x7c, 0x68,
	0x03, 0xaa, 0x54, 0x8b, 0x32, 0x31, 0x71, 0x54, 0xfc, 0x08, 0xd8, 0x35, 0xd8, 0xba, 0xfd, 0x6b,
	0x4d, 0xd6, 0x1b, 0x7c, 0xff, 0x40, 0x1f, 0xe4, 0x15, 0x64, 0x74, 0x38, 0x78, 0x0c, 0x3c, 0x7f,
	0x6b, 0x66, 0x92, 0x97, 0xb0, 0x1e, 0xfa, 0x63, 0x1f, 0x66, 0x83, 0x3f, 0x88, 0xa6, 0xb0, 0x5d,
	0xc2, 0x5d, 0x1c, 0xc9, 0x6b, 0xc8, 0x7d, 0x68, 0x5d, 0x88, 0x2c, 0xfe, 0x83, 0xc9, 0x1f, 0x4f,
	0x1d, 0x77, 0x6b, 0xee, 0x16, 0x94, 0x37, 0x00, 0x9e, 0xe5, 0x9e, 0xc9, 0x75, 0x2a, 0xe3, 0xe5,
	0xa2, 0xa4, 0x78, 0x02, 0x19, 0xcb, 0xfb, 0x91, 0x4e, 0x1e, 0xe5, 0x2d, 0xa4, 0x03, 0x59, 0xaf,
	0x84, 0x4e, 0xca, 0xcd, 0xdd, 0xae, 0x8a, 0xaf, 0x5b, 0xd5, 0x64, 0x0d, 0xd7, 0x7c, 0xb6, 0xf6,
	0x6b, 0xfa, 0x93, 0xd7, 0x49, 0xcd, 0x82, 0x2f, 0x19, 0x3f, 0xcb, 0xfd, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xcf, 0xd3, 0xe2, 0x2a, 0xa3, 0x01, 0x00, 0x00,
}
