// Code generated by protoc-gen-go.
// source: schedule.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Schedule struct {
	Id   uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Schedule) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Schedule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SearchSchedulesRequest struct {
	Offset uint32 `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *SearchSchedulesRequest) Reset()                    { *m = SearchSchedulesRequest{} }
func (m *SearchSchedulesRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchSchedulesRequest) ProtoMessage()               {}
func (*SearchSchedulesRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SearchSchedulesRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchSchedulesRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SearchSchedulesResponse struct {
	Schedules    []*Schedule `protobuf:"bytes,1,rep,name=schedules" json:"schedules,omitempty"`
	MaxSchedules uint32      `protobuf:"varint,2,opt,name=maxSchedules" json:"maxSchedules,omitempty"`
}

func (m *SearchSchedulesResponse) Reset()                    { *m = SearchSchedulesResponse{} }
func (m *SearchSchedulesResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchSchedulesResponse) ProtoMessage()               {}
func (*SearchSchedulesResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *SearchSchedulesResponse) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

func (m *SearchSchedulesResponse) GetMaxSchedules() uint32 {
	if m != nil {
		return m.MaxSchedules
	}
	return 0
}

type FetchScheduleByIdRequest struct {
	ScheduleIds []uint32 `protobuf:"varint,1,rep,packed,name=scheduleIds" json:"scheduleIds,omitempty"`
}

func (m *FetchScheduleByIdRequest) Reset()                    { *m = FetchScheduleByIdRequest{} }
func (m *FetchScheduleByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchScheduleByIdRequest) ProtoMessage()               {}
func (*FetchScheduleByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *FetchScheduleByIdRequest) GetScheduleIds() []uint32 {
	if m != nil {
		return m.ScheduleIds
	}
	return nil
}

type FetchScheduleByIdResponse struct {
	Schedules []*Schedule `protobuf:"bytes,1,rep,name=schedules" json:"schedules,omitempty"`
}

func (m *FetchScheduleByIdResponse) Reset()                    { *m = FetchScheduleByIdResponse{} }
func (m *FetchScheduleByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchScheduleByIdResponse) ProtoMessage()               {}
func (*FetchScheduleByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *FetchScheduleByIdResponse) GetSchedules() []*Schedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

type CreateScheduleRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateScheduleRequest) Reset()                    { *m = CreateScheduleRequest{} }
func (m *CreateScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateScheduleRequest) ProtoMessage()               {}
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *CreateScheduleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateScheduleResponse struct {
	Schedule *Schedule `protobuf:"bytes,1,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *CreateScheduleResponse) Reset()                    { *m = CreateScheduleResponse{} }
func (m *CreateScheduleResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateScheduleResponse) ProtoMessage()               {}
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *CreateScheduleResponse) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type UpdateScheduleRequest struct {
	ScheduleId    uint32   `protobuf:"varint,1,opt,name=scheduleId" json:"scheduleId,omitempty"`
	Name          string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	AddSongIds    []uint32 `protobuf:"varint,3,rep,packed,name=addSongIds" json:"addSongIds,omitempty"`
	RemoveSongIds []uint32 `protobuf:"varint,4,rep,packed,name=removeSongIds" json:"removeSongIds,omitempty"`
}

func (m *UpdateScheduleRequest) Reset()                    { *m = UpdateScheduleRequest{} }
func (m *UpdateScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateScheduleRequest) ProtoMessage()               {}
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *UpdateScheduleRequest) GetScheduleId() uint32 {
	if m != nil {
		return m.ScheduleId
	}
	return 0
}

func (m *UpdateScheduleRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateScheduleRequest) GetAddSongIds() []uint32 {
	if m != nil {
		return m.AddSongIds
	}
	return nil
}

func (m *UpdateScheduleRequest) GetRemoveSongIds() []uint32 {
	if m != nil {
		return m.RemoveSongIds
	}
	return nil
}

type UpdateScheduleResponse struct {
	Schedule *Schedule `protobuf:"bytes,1,opt,name=schedule" json:"schedule,omitempty"`
	Success  bool      `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *UpdateScheduleResponse) Reset()                    { *m = UpdateScheduleResponse{} }
func (m *UpdateScheduleResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateScheduleResponse) ProtoMessage()               {}
func (*UpdateScheduleResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *UpdateScheduleResponse) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

func (m *UpdateScheduleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RemoveScheduleRequest struct {
	ScheduleId uint32 `protobuf:"varint,1,opt,name=scheduleId" json:"scheduleId,omitempty"`
}

func (m *RemoveScheduleRequest) Reset()                    { *m = RemoveScheduleRequest{} }
func (m *RemoveScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveScheduleRequest) ProtoMessage()               {}
func (*RemoveScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *RemoveScheduleRequest) GetScheduleId() uint32 {
	if m != nil {
		return m.ScheduleId
	}
	return 0
}

type RemoveScheduleResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *RemoveScheduleResponse) Reset()                    { *m = RemoveScheduleResponse{} }
func (m *RemoveScheduleResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveScheduleResponse) ProtoMessage()               {}
func (*RemoveScheduleResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *RemoveScheduleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Schedule)(nil), "SeppoService.Schedule")
	proto.RegisterType((*SearchSchedulesRequest)(nil), "SeppoService.SearchSchedulesRequest")
	proto.RegisterType((*SearchSchedulesResponse)(nil), "SeppoService.SearchSchedulesResponse")
	proto.RegisterType((*FetchScheduleByIdRequest)(nil), "SeppoService.FetchScheduleByIdRequest")
	proto.RegisterType((*FetchScheduleByIdResponse)(nil), "SeppoService.FetchScheduleByIdResponse")
	proto.RegisterType((*CreateScheduleRequest)(nil), "SeppoService.CreateScheduleRequest")
	proto.RegisterType((*CreateScheduleResponse)(nil), "SeppoService.CreateScheduleResponse")
	proto.RegisterType((*UpdateScheduleRequest)(nil), "SeppoService.UpdateScheduleRequest")
	proto.RegisterType((*UpdateScheduleResponse)(nil), "SeppoService.UpdateScheduleResponse")
	proto.RegisterType((*RemoveScheduleRequest)(nil), "SeppoService.RemoveScheduleRequest")
	proto.RegisterType((*RemoveScheduleResponse)(nil), "SeppoService.RemoveScheduleResponse")
}

func init() { proto.RegisterFile("schedule.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcf, 0x4f, 0xfa, 0x30,
	0x14, 0x4f, 0x81, 0x2f, 0x5f, 0x78, 0x30, 0x0e, 0x8d, 0xcc, 0x79, 0x31, 0x4b, 0xe3, 0x81, 0xc4,
	0x64, 0x07, 0x34, 0xf1, 0xe2, 0x49, 0x13, 0x12, 0x12, 0x2f, 0x76, 0xf1, 0x0f, 0x98, 0xeb, 0x43,
	0x96, 0x30, 0x3a, 0xd7, 0x41, 0xf4, 0xcf, 0xf0, 0x3f, 0x36, 0x74, 0x2d, 0x14, 0xc4, 0x83, 0x7a,
	0xdb, 0x7b, 0xfd, 0xfc, 0x7a, 0x6f, 0x2d, 0x0c, 0x54, 0x3a, 0x47, 0xb1, 0x5a, 0x60, 0x54, 0x94,
	0xb2, 0x92, 0xb4, 0x1f, 0x63, 0x51, 0xc8, 0x18, 0xcb, 0x75, 0x96, 0x22, 0x8b, 0xa0, 0x13, 0x9b,
	0x73, 0x3a, 0x80, 0x46, 0x26, 0x02, 0x12, 0x92, 0x91, 0xc7, 0x1b, 0x99, 0xa0, 0x14, 0x5a, 0xcb,
	0x24, 0xc7, 0xa0, 0x11, 0x92, 0x51, 0x97, 0xeb, 0x6f, 0x36, 0x01, 0x3f, 0xc6, 0xa4, 0x4c, 0xe7,
	0x96, 0xa5, 0x38, 0xbe, 0xae, 0x50, 0x55, 0xd4, 0x87, 0xb6, 0x9c, 0xcd, 0x14, 0x56, 0x46, 0xc1,
	0x54, 0xf4, 0x04, 0xfe, 0x2d, 0xb2, 0x3c, 0xab, 0xb4, 0x8c, 0xc7, 0xeb, 0x82, 0x29, 0x38, 0xfd,
	0xa2, 0xa3, 0x0a, 0xb9, 0x54, 0x48, 0xaf, 0xa1, 0x6b, 0x23, 0xab, 0x80, 0x84, 0xcd, 0x51, 0x6f,
	0xec, 0x47, 0x6e, 0xe8, 0xc8, 0x72, 0xf8, 0x0e, 0x48, 0x19, 0xf4, 0xf3, 0xe4, 0x6d, 0xab, 0x66,
	0xdc, 0xf6, 0x7a, 0xec, 0x16, 0x82, 0x09, 0x56, 0x3b, 0xcf, 0xbb, 0xf7, 0xa9, 0xb0, 0xf1, 0x43,
	0xe8, 0x59, 0xb1, 0xa9, 0xa8, 0x7d, 0x3d, 0xee, 0xb6, 0xd8, 0x23, 0x9c, 0x1d, 0x61, 0xff, 0x25,
	0x34, 0xbb, 0x84, 0xe1, 0x7d, 0x89, 0x49, 0x85, 0xdb, 0x43, 0x93, 0xc6, 0xae, 0x9e, 0x38, 0xab,
	0x7f, 0x00, 0xff, 0x10, 0x6c, 0xcc, 0xc7, 0xd0, 0xb1, 0x9a, 0x9a, 0xf1, 0xbd, 0xf7, 0x16, 0xc7,
	0x3e, 0x08, 0x0c, 0x9f, 0x0a, 0x71, 0xc4, 0xfb, 0x1c, 0x60, 0x37, 0xb6, 0xf9, 0x99, 0x4e, 0xe7,
	0xd8, 0xb5, 0xd8, 0x70, 0x12, 0x21, 0x62, 0xb9, 0x7c, 0xd9, 0x2c, 0xaf, 0xa9, 0x97, 0xe7, 0x74,
	0xe8, 0x05, 0x78, 0x25, 0xe6, 0x72, 0x8d, 0x16, 0xd2, 0xd2, 0x90, 0xfd, 0x26, 0x9b, 0x81, 0x7f,
	0x18, 0xe9, 0xf7, 0x13, 0xd2, 0x00, 0xfe, 0xab, 0x55, 0x9a, 0xa2, 0xaa, 0x2f, 0x43, 0x87, 0xdb,
	0x92, 0xdd, 0xc0, 0x90, 0xd7, 0xc6, 0x3f, 0x1b, 0x9d, 0x8d, 0xc1, 0x3f, 0x24, 0x9a, 0x80, 0x8e,
	0x19, 0xd9, 0x33, 0x7b, 0x6e, 0xeb, 0x67, 0x77, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0x33, 0x60,
	0xa3, 0xf4, 0x88, 0x03, 0x00, 0x00,
}
