// Code generated by protoc-gen-go.
// source: seppo_service.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Seppo service

type SeppoClient interface {
	ListenForChangedEwSong(ctx context.Context, in *ListenForChangedEwSongRequest, opts ...grpc.CallOption) (Seppo_ListenForChangedEwSongClient, error)
	SyncEwDatabase(ctx context.Context, in *SyncEwDatabaseRequest, opts ...grpc.CallOption) (*SyncEwDatabaseResponse, error)
}

type seppoClient struct {
	cc *grpc.ClientConn
}

func NewSeppoClient(cc *grpc.ClientConn) SeppoClient {
	return &seppoClient{cc}
}

func (c *seppoClient) ListenForChangedEwSong(ctx context.Context, in *ListenForChangedEwSongRequest, opts ...grpc.CallOption) (Seppo_ListenForChangedEwSongClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Seppo_serviceDesc.Streams[0], c.cc, "/SeppoService.Seppo/listenForChangedEwSong", opts...)
	if err != nil {
		return nil, err
	}
	x := &seppoListenForChangedEwSongClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Seppo_ListenForChangedEwSongClient interface {
	Recv() (*EwSong, error)
	grpc.ClientStream
}

type seppoListenForChangedEwSongClient struct {
	grpc.ClientStream
}

func (x *seppoListenForChangedEwSongClient) Recv() (*EwSong, error) {
	m := new(EwSong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *seppoClient) SyncEwDatabase(ctx context.Context, in *SyncEwDatabaseRequest, opts ...grpc.CallOption) (*SyncEwDatabaseResponse, error) {
	out := new(SyncEwDatabaseResponse)
	err := grpc.Invoke(ctx, "/SeppoService.Seppo/syncEwDatabase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Seppo service

type SeppoServer interface {
	ListenForChangedEwSong(*ListenForChangedEwSongRequest, Seppo_ListenForChangedEwSongServer) error
	SyncEwDatabase(context.Context, *SyncEwDatabaseRequest) (*SyncEwDatabaseResponse, error)
}

func RegisterSeppoServer(s *grpc.Server, srv SeppoServer) {
	s.RegisterService(&_Seppo_serviceDesc, srv)
}

func _Seppo_ListenForChangedEwSong_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenForChangedEwSongRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SeppoServer).ListenForChangedEwSong(m, &seppoListenForChangedEwSongServer{stream})
}

type Seppo_ListenForChangedEwSongServer interface {
	Send(*EwSong) error
	grpc.ServerStream
}

type seppoListenForChangedEwSongServer struct {
	grpc.ServerStream
}

func (x *seppoListenForChangedEwSongServer) Send(m *EwSong) error {
	return x.ServerStream.SendMsg(m)
}

func _Seppo_SyncEwDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncEwDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeppoServer).SyncEwDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SeppoService.Seppo/SyncEwDatabase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeppoServer).SyncEwDatabase(ctx, req.(*SyncEwDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Seppo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SeppoService.Seppo",
	HandlerType: (*SeppoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "syncEwDatabase",
			Handler:    _Seppo_SyncEwDatabase_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "listenForChangedEwSong",
			Handler:       _Seppo_ListenForChangedEwSong_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "seppo_service.proto",
}

func init() { proto.RegisterFile("seppo_service.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4e, 0x2d, 0x28,
	0xc8, 0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x09, 0x06, 0x09, 0x06, 0x43, 0xc4, 0xa4, 0x04, 0x53, 0xcb, 0xe3, 0x53, 0x12, 0x4b, 0x12,
	0x93, 0x12, 0x8b, 0xa1, 0x0a, 0xa4, 0x78, 0x53, 0xcb, 0xe3, 0x8b, 0xf3, 0xf3, 0xd2, 0xa1, 0x5c,
	0xbe, 0xd4, 0xf2, 0xf8, 0xb2, 0xd4, 0x22, 0x98, 0xb4, 0xd1, 0x71, 0x46, 0x2e, 0x56, 0xb0, 0x11,
	0x42, 0xf1, 0x5c, 0x62, 0x39, 0x99, 0xc5, 0x25, 0xa9, 0x79, 0x6e, 0xf9, 0x45, 0xce, 0x19, 0x89,
	0x79, 0xe9, 0xa9, 0x29, 0xae, 0xe5, 0xc1, 0xf9, 0x79, 0xe9, 0x42, 0xda, 0x7a, 0xc8, 0x96, 0xe8,
	0xf9, 0x60, 0x55, 0x15, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x25, 0x82, 0xaa, 0x18, 0x22,
	0xa9, 0xc4, 0x60, 0xc0, 0x28, 0x14, 0xcb, 0xc5, 0x57, 0x5c, 0x99, 0x97, 0xec, 0x5a, 0xee, 0x02,
	0x75, 0xa1, 0x90, 0x32, 0xaa, 0xda, 0x60, 0x14, 0x59, 0x98, 0x81, 0x2a, 0xf8, 0x15, 0x15, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x31, 0x24, 0xb1, 0x81, 0x3d, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xec, 0xb3, 0x11, 0xcc, 0x27, 0x01, 0x00, 0x00,
}
