// Code generated by protoc-gen-go.
// source: song_database.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SongDatabase struct {
	Id      uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Version uint64 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *SongDatabase) Reset()                    { *m = SongDatabase{} }
func (m *SongDatabase) String() string            { return proto.CompactTextString(m) }
func (*SongDatabase) ProtoMessage()               {}
func (*SongDatabase) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *SongDatabase) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SongDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SongDatabase) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SongDatabaseEdge struct {
	Node   *SongDatabase `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32        `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *SongDatabaseEdge) Reset()                    { *m = SongDatabaseEdge{} }
func (m *SongDatabaseEdge) String() string            { return proto.CompactTextString(m) }
func (*SongDatabaseEdge) ProtoMessage()               {}
func (*SongDatabaseEdge) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SongDatabaseEdge) GetNode() *SongDatabase {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SongDatabaseEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type SongDatabasesConnection struct {
	Edges      []*SongDatabaseEdge `protobuf:"bytes,1,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32              `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *SongDatabasesConnection) Reset()                    { *m = SongDatabasesConnection{} }
func (m *SongDatabasesConnection) String() string            { return proto.CompactTextString(m) }
func (*SongDatabasesConnection) ProtoMessage()               {}
func (*SongDatabasesConnection) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *SongDatabasesConnection) GetEdges() []*SongDatabaseEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *SongDatabasesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type FetchSongDatabasesRequest struct {
	After  uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First  uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last   uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
}

func (m *FetchSongDatabasesRequest) Reset()                    { *m = FetchSongDatabasesRequest{} }
func (m *FetchSongDatabasesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabasesRequest) ProtoMessage()               {}
func (*FetchSongDatabasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *FetchSongDatabasesRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

type FetchSongDatabaseByIdRequest struct {
	SongDatabasesIds []uint32 `protobuf:"varint,1,rep,packed,name=songDatabasesIds" json:"songDatabasesIds,omitempty"`
}

func (m *FetchSongDatabaseByIdRequest) Reset()                    { *m = FetchSongDatabaseByIdRequest{} }
func (m *FetchSongDatabaseByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabaseByIdRequest) ProtoMessage()               {}
func (*FetchSongDatabaseByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{4} }

func (m *FetchSongDatabaseByIdRequest) GetSongDatabasesIds() []uint32 {
	if m != nil {
		return m.SongDatabasesIds
	}
	return nil
}

type FetchSongDatabaseByIdResponse struct {
	SongDatabases []*SongDatabase `protobuf:"bytes,1,rep,name=songDatabases" json:"songDatabases,omitempty"`
}

func (m *FetchSongDatabaseByIdResponse) Reset()                    { *m = FetchSongDatabaseByIdResponse{} }
func (m *FetchSongDatabaseByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabaseByIdResponse) ProtoMessage()               {}
func (*FetchSongDatabaseByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{5} }

func (m *FetchSongDatabaseByIdResponse) GetSongDatabases() []*SongDatabase {
	if m != nil {
		return m.SongDatabases
	}
	return nil
}

type CreateSongDatabaseRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateSongDatabaseRequest) Reset()                    { *m = CreateSongDatabaseRequest{} }
func (m *CreateSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSongDatabaseRequest) ProtoMessage()               {}
func (*CreateSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{6} }

func (m *CreateSongDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateSongDatabaseResponse struct {
	SongDatabase *SongDatabase `protobuf:"bytes,1,opt,name=songDatabase" json:"songDatabase,omitempty"`
}

func (m *CreateSongDatabaseResponse) Reset()                    { *m = CreateSongDatabaseResponse{} }
func (m *CreateSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSongDatabaseResponse) ProtoMessage()               {}
func (*CreateSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{7} }

func (m *CreateSongDatabaseResponse) GetSongDatabase() *SongDatabase {
	if m != nil {
		return m.SongDatabase
	}
	return nil
}

type EditSongDatabaseRequest struct {
	SongDatabaseId uint32 `protobuf:"varint,1,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EditSongDatabaseRequest) Reset()                    { *m = EditSongDatabaseRequest{} }
func (m *EditSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*EditSongDatabaseRequest) ProtoMessage()               {}
func (*EditSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{8} }

func (m *EditSongDatabaseRequest) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

func (m *EditSongDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EditSongDatabaseResponse struct {
	SongDatabase *SongDatabase `protobuf:"bytes,1,opt,name=songDatabase" json:"songDatabase,omitempty"`
}

func (m *EditSongDatabaseResponse) Reset()                    { *m = EditSongDatabaseResponse{} }
func (m *EditSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*EditSongDatabaseResponse) ProtoMessage()               {}
func (*EditSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{9} }

func (m *EditSongDatabaseResponse) GetSongDatabase() *SongDatabase {
	if m != nil {
		return m.SongDatabase
	}
	return nil
}

type RemoveSongDatabaseRequest struct {
	SongDatabaseId uint32 `protobuf:"varint,1,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
}

func (m *RemoveSongDatabaseRequest) Reset()                    { *m = RemoveSongDatabaseRequest{} }
func (m *RemoveSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveSongDatabaseRequest) ProtoMessage()               {}
func (*RemoveSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{10} }

func (m *RemoveSongDatabaseRequest) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

type RemoveSongDatabaseResponse struct {
}

func (m *RemoveSongDatabaseResponse) Reset()                    { *m = RemoveSongDatabaseResponse{} }
func (m *RemoveSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveSongDatabaseResponse) ProtoMessage()               {}
func (*RemoveSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{11} }

func init() {
	proto.RegisterType((*SongDatabase)(nil), "SeppoService.SongDatabase")
	proto.RegisterType((*SongDatabaseEdge)(nil), "SeppoService.SongDatabaseEdge")
	proto.RegisterType((*SongDatabasesConnection)(nil), "SeppoService.SongDatabasesConnection")
	proto.RegisterType((*FetchSongDatabasesRequest)(nil), "SeppoService.FetchSongDatabasesRequest")
	proto.RegisterType((*FetchSongDatabaseByIdRequest)(nil), "SeppoService.FetchSongDatabaseByIdRequest")
	proto.RegisterType((*FetchSongDatabaseByIdResponse)(nil), "SeppoService.FetchSongDatabaseByIdResponse")
	proto.RegisterType((*CreateSongDatabaseRequest)(nil), "SeppoService.CreateSongDatabaseRequest")
	proto.RegisterType((*CreateSongDatabaseResponse)(nil), "SeppoService.CreateSongDatabaseResponse")
	proto.RegisterType((*EditSongDatabaseRequest)(nil), "SeppoService.EditSongDatabaseRequest")
	proto.RegisterType((*EditSongDatabaseResponse)(nil), "SeppoService.EditSongDatabaseResponse")
	proto.RegisterType((*RemoveSongDatabaseRequest)(nil), "SeppoService.RemoveSongDatabaseRequest")
	proto.RegisterType((*RemoveSongDatabaseResponse)(nil), "SeppoService.RemoveSongDatabaseResponse")
}

func init() { proto.RegisterFile("song_database.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xd1, 0x6b, 0xd4, 0x40,
	0x10, 0xc6, 0xc9, 0xf5, 0x5a, 0x71, 0x7a, 0x29, 0x65, 0x15, 0x9b, 0x3b, 0x6a, 0x39, 0xf6, 0x41,
	0x0e, 0x1f, 0x22, 0x54, 0x9f, 0x45, 0x8c, 0x15, 0x4e, 0x7c, 0xda, 0xc3, 0x97, 0x22, 0xc8, 0x5e,
	0x76, 0x2e, 0x06, 0xda, 0x9d, 0xb8, 0xbb, 0x77, 0xe0, 0x7f, 0x2f, 0xd9, 0x24, 0xb8, 0xf1, 0x72,
	0x22, 0xd8, 0xb7, 0x9d, 0xe1, 0xdb, 0xef, 0xfb, 0xed, 0x64, 0x02, 0x4f, 0x2c, 0xe9, 0xe2, 0x9b,
	0x92, 0x4e, 0xae, 0xa5, 0xc5, 0xb4, 0x32, 0xe4, 0x88, 0x4d, 0x56, 0x58, 0x55, 0xb4, 0x42, 0xb3,
	0x2b, 0x73, 0xe4, 0x9f, 0x61, 0xb2, 0x22, 0x5d, 0x7c, 0x68, 0x35, 0xec, 0x0c, 0x46, 0xa5, 0x4a,
	0xa2, 0x79, 0xb4, 0x88, 0xc5, 0xa8, 0x54, 0x8c, 0xc1, 0x58, 0xcb, 0x7b, 0x4c, 0x46, 0xf3, 0x68,
	0xf1, 0x58, 0xf8, 0x33, 0x4b, 0xe0, 0xd1, 0x0e, 0x8d, 0x2d, 0x49, 0x27, 0x47, 0xf3, 0x68, 0x31,
	0x16, 0x5d, 0xc9, 0x6f, 0xe1, 0x3c, 0x74, 0xbb, 0x51, 0x05, 0xb2, 0x14, 0xc6, 0x9a, 0x14, 0x7a,
	0xcf, 0xd3, 0xeb, 0x59, 0x1a, 0xc6, 0xa7, 0xa1, 0x5a, 0x78, 0x1d, 0x7b, 0x06, 0x27, 0xf9, 0xd6,
	0x58, 0x32, 0x3e, 0x33, 0x16, 0x6d, 0xc5, 0x09, 0x2e, 0x42, 0xb5, 0xcd, 0x48, 0x6b, 0xcc, 0x5d,
	0x49, 0x9a, 0xbd, 0x81, 0x63, 0x54, 0x05, 0xda, 0x24, 0x9a, 0x1f, 0x2d, 0x4e, 0xaf, 0xaf, 0x0e,
	0x67, 0xd4, 0x44, 0xa2, 0x11, 0xb3, 0x2b, 0x00, 0x47, 0x4e, 0xde, 0x65, 0xb4, 0xd5, 0xce, 0xbf,
	0x24, 0x16, 0x41, 0x87, 0x5b, 0x98, 0x7e, 0x44, 0x97, 0x7f, 0xef, 0xa5, 0x0a, 0xfc, 0xb1, 0x45,
	0xeb, 0xd8, 0x53, 0x38, 0x96, 0x1b, 0x87, 0xa6, 0x1d, 0x55, 0x53, 0xd4, 0xec, 0x6b, 0xdc, 0x90,
	0xc1, 0x8e, 0xbd, 0xa9, 0x6a, 0xf5, 0xa6, 0x34, 0xb6, 0x4b, 0x69, 0x8a, 0x7a, 0xb6, 0x77, 0xd2,
	0xba, 0x64, 0xec, 0x9b, 0xfe, 0xcc, 0x3f, 0xc1, 0xe5, 0x5e, 0xe8, 0xfb, 0x9f, 0x4b, 0xd5, 0xe5,
	0xbe, 0x84, 0x73, 0x1b, 0xf2, 0x2c, 0x55, 0xf3, 0xea, 0x58, 0xec, 0xf5, 0xb9, 0x84, 0xe7, 0x07,
	0xbc, 0x6c, 0x45, 0xda, 0x22, 0x7b, 0x07, 0x71, 0xef, 0x52, 0x3b, 0xbf, 0xbf, 0x7d, 0xa3, 0xfe,
	0x05, 0xfe, 0x0a, 0xa6, 0x99, 0x41, 0xe9, 0xb0, 0x27, 0x6a, 0x59, 0xbb, 0xdd, 0x89, 0x7e, 0xef,
	0x0e, 0xff, 0x0a, 0xb3, 0xa1, 0x0b, 0x2d, 0xd0, 0x5b, 0x98, 0x84, 0xfe, 0xff, 0xb0, 0x33, 0x3d,
	0x3d, 0xff, 0x02, 0x17, 0x37, 0xaa, 0x74, 0x43, 0x30, 0x2f, 0xe0, 0x2c, 0x94, 0x2e, 0xbb, 0x25,
	0xff, 0xa3, 0x3b, 0xb4, 0xf0, 0xfc, 0x16, 0x92, 0x7d, 0xdb, 0x07, 0x42, 0xce, 0x60, 0x2a, 0xf0,
	0x9e, 0x76, 0xf8, 0x1f, 0xd0, 0xfc, 0x12, 0x66, 0x43, 0x26, 0x0d, 0xe2, 0xfa, 0xc4, 0xff, 0xf8,
	0xaf, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xac, 0xa1, 0xd4, 0x0f, 0x04, 0x00, 0x00,
}
