// Code generated by protoc-gen-go.
// source: song_database.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SongDatabase struct {
	Id      uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Version uint64 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (m *SongDatabase) Reset()                    { *m = SongDatabase{} }
func (m *SongDatabase) String() string            { return proto.CompactTextString(m) }
func (*SongDatabase) ProtoMessage()               {}
func (*SongDatabase) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *SongDatabase) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SongDatabase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SongDatabase) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type SongDatabaseEdge struct {
	Node   *SongDatabase `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	Cursor uint32        `protobuf:"varint,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *SongDatabaseEdge) Reset()                    { *m = SongDatabaseEdge{} }
func (m *SongDatabaseEdge) String() string            { return proto.CompactTextString(m) }
func (*SongDatabaseEdge) ProtoMessage()               {}
func (*SongDatabaseEdge) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *SongDatabaseEdge) GetNode() *SongDatabase {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *SongDatabaseEdge) GetCursor() uint32 {
	if m != nil {
		return m.Cursor
	}
	return 0
}

type SongDatabasesConnection struct {
	Edges      []*SongDatabaseEdge `protobuf:"bytes,1,rep,name=edges" json:"edges,omitempty"`
	TotalCount uint32              `protobuf:"varint,3,opt,name=totalCount" json:"totalCount,omitempty"`
}

func (m *SongDatabasesConnection) Reset()                    { *m = SongDatabasesConnection{} }
func (m *SongDatabasesConnection) String() string            { return proto.CompactTextString(m) }
func (*SongDatabasesConnection) ProtoMessage()               {}
func (*SongDatabasesConnection) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *SongDatabasesConnection) GetEdges() []*SongDatabaseEdge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *SongDatabasesConnection) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type FetchSongDatabasesRequest struct {
	After       uint32 `protobuf:"varint,1,opt,name=after" json:"after,omitempty"`
	Before      uint32 `protobuf:"varint,2,opt,name=before" json:"before,omitempty"`
	First       uint32 `protobuf:"varint,3,opt,name=first" json:"first,omitempty"`
	Last        uint32 `protobuf:"varint,4,opt,name=last" json:"last,omitempty"`
	SearchWord  string `protobuf:"bytes,5,opt,name=searchWord" json:"searchWord,omitempty"`
	VariationId uint32 `protobuf:"varint,6,opt,name=variationId" json:"variationId,omitempty"`
}

func (m *FetchSongDatabasesRequest) Reset()                    { *m = FetchSongDatabasesRequest{} }
func (m *FetchSongDatabasesRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabasesRequest) ProtoMessage()               {}
func (*FetchSongDatabasesRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

func (m *FetchSongDatabasesRequest) GetAfter() uint32 {
	if m != nil {
		return m.After
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetBefore() uint32 {
	if m != nil {
		return m.Before
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetFirst() uint32 {
	if m != nil {
		return m.First
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetLast() uint32 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *FetchSongDatabasesRequest) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *FetchSongDatabasesRequest) GetVariationId() uint32 {
	if m != nil {
		return m.VariationId
	}
	return 0
}

type FetchSongDatabaseByIdRequest struct {
	SongDatabaseIds []uint32 `protobuf:"varint,1,rep,packed,name=songDatabaseIds" json:"songDatabaseIds,omitempty"`
}

func (m *FetchSongDatabaseByIdRequest) Reset()                    { *m = FetchSongDatabaseByIdRequest{} }
func (m *FetchSongDatabaseByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabaseByIdRequest) ProtoMessage()               {}
func (*FetchSongDatabaseByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *FetchSongDatabaseByIdRequest) GetSongDatabaseIds() []uint32 {
	if m != nil {
		return m.SongDatabaseIds
	}
	return nil
}

type FetchSongDatabaseByIdResponse struct {
	SongDatabases []*SongDatabase `protobuf:"bytes,1,rep,name=songDatabases" json:"songDatabases,omitempty"`
}

func (m *FetchSongDatabaseByIdResponse) Reset()                    { *m = FetchSongDatabaseByIdResponse{} }
func (m *FetchSongDatabaseByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchSongDatabaseByIdResponse) ProtoMessage()               {}
func (*FetchSongDatabaseByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *FetchSongDatabaseByIdResponse) GetSongDatabases() []*SongDatabase {
	if m != nil {
		return m.SongDatabases
	}
	return nil
}

type FetchTagsBySongDatabaseIdRequest struct {
}

func (m *FetchTagsBySongDatabaseIdRequest) Reset()         { *m = FetchTagsBySongDatabaseIdRequest{} }
func (m *FetchTagsBySongDatabaseIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchTagsBySongDatabaseIdRequest) ProtoMessage()    {}
func (*FetchTagsBySongDatabaseIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{6}
}

type FetchTagsBySongDatabaseIdResponse struct {
}

func (m *FetchTagsBySongDatabaseIdResponse) Reset()         { *m = FetchTagsBySongDatabaseIdResponse{} }
func (m *FetchTagsBySongDatabaseIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchTagsBySongDatabaseIdResponse) ProtoMessage()    {}
func (*FetchTagsBySongDatabaseIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor7, []int{7}
}

type CreateSongDatabaseRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *CreateSongDatabaseRequest) Reset()                    { *m = CreateSongDatabaseRequest{} }
func (m *CreateSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSongDatabaseRequest) ProtoMessage()               {}
func (*CreateSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *CreateSongDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateSongDatabaseResponse struct {
	SongDatabase *SongDatabase `protobuf:"bytes,1,opt,name=songDatabase" json:"songDatabase,omitempty"`
}

func (m *CreateSongDatabaseResponse) Reset()                    { *m = CreateSongDatabaseResponse{} }
func (m *CreateSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSongDatabaseResponse) ProtoMessage()               {}
func (*CreateSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *CreateSongDatabaseResponse) GetSongDatabase() *SongDatabase {
	if m != nil {
		return m.SongDatabase
	}
	return nil
}

type EditSongDatabaseRequest struct {
	SongDatabaseId uint32   `protobuf:"varint,1,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
	Name           string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	AddTagIds      []uint32 `protobuf:"varint,3,rep,packed,name=addTagIds" json:"addTagIds,omitempty"`
	RemoveTagIds   []uint32 `protobuf:"varint,4,rep,packed,name=removeTagIds" json:"removeTagIds,omitempty"`
}

func (m *EditSongDatabaseRequest) Reset()                    { *m = EditSongDatabaseRequest{} }
func (m *EditSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*EditSongDatabaseRequest) ProtoMessage()               {}
func (*EditSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *EditSongDatabaseRequest) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

func (m *EditSongDatabaseRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditSongDatabaseRequest) GetAddTagIds() []uint32 {
	if m != nil {
		return m.AddTagIds
	}
	return nil
}

func (m *EditSongDatabaseRequest) GetRemoveTagIds() []uint32 {
	if m != nil {
		return m.RemoveTagIds
	}
	return nil
}

type EditSongDatabaseResponse struct {
	SongDatabase *SongDatabase `protobuf:"bytes,1,opt,name=songDatabase" json:"songDatabase,omitempty"`
}

func (m *EditSongDatabaseResponse) Reset()                    { *m = EditSongDatabaseResponse{} }
func (m *EditSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*EditSongDatabaseResponse) ProtoMessage()               {}
func (*EditSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *EditSongDatabaseResponse) GetSongDatabase() *SongDatabase {
	if m != nil {
		return m.SongDatabase
	}
	return nil
}

type RemoveSongDatabaseRequest struct {
	SongDatabaseId uint32 `protobuf:"varint,1,opt,name=songDatabaseId" json:"songDatabaseId,omitempty"`
}

func (m *RemoveSongDatabaseRequest) Reset()                    { *m = RemoveSongDatabaseRequest{} }
func (m *RemoveSongDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveSongDatabaseRequest) ProtoMessage()               {}
func (*RemoveSongDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{12} }

func (m *RemoveSongDatabaseRequest) GetSongDatabaseId() uint32 {
	if m != nil {
		return m.SongDatabaseId
	}
	return 0
}

type RemoveSongDatabaseResponse struct {
}

func (m *RemoveSongDatabaseResponse) Reset()                    { *m = RemoveSongDatabaseResponse{} }
func (m *RemoveSongDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveSongDatabaseResponse) ProtoMessage()               {}
func (*RemoveSongDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{13} }

func init() {
	proto.RegisterType((*SongDatabase)(nil), "SeppoService.SongDatabase")
	proto.RegisterType((*SongDatabaseEdge)(nil), "SeppoService.SongDatabaseEdge")
	proto.RegisterType((*SongDatabasesConnection)(nil), "SeppoService.SongDatabasesConnection")
	proto.RegisterType((*FetchSongDatabasesRequest)(nil), "SeppoService.FetchSongDatabasesRequest")
	proto.RegisterType((*FetchSongDatabaseByIdRequest)(nil), "SeppoService.FetchSongDatabaseByIdRequest")
	proto.RegisterType((*FetchSongDatabaseByIdResponse)(nil), "SeppoService.FetchSongDatabaseByIdResponse")
	proto.RegisterType((*FetchTagsBySongDatabaseIdRequest)(nil), "SeppoService.FetchTagsBySongDatabaseIdRequest")
	proto.RegisterType((*FetchTagsBySongDatabaseIdResponse)(nil), "SeppoService.FetchTagsBySongDatabaseIdResponse")
	proto.RegisterType((*CreateSongDatabaseRequest)(nil), "SeppoService.CreateSongDatabaseRequest")
	proto.RegisterType((*CreateSongDatabaseResponse)(nil), "SeppoService.CreateSongDatabaseResponse")
	proto.RegisterType((*EditSongDatabaseRequest)(nil), "SeppoService.EditSongDatabaseRequest")
	proto.RegisterType((*EditSongDatabaseResponse)(nil), "SeppoService.EditSongDatabaseResponse")
	proto.RegisterType((*RemoveSongDatabaseRequest)(nil), "SeppoService.RemoveSongDatabaseRequest")
	proto.RegisterType((*RemoveSongDatabaseResponse)(nil), "SeppoService.RemoveSongDatabaseResponse")
}

func init() { proto.RegisterFile("song_database.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x65, 0x93, 0x4d, 0xa4, 0x37, 0xd9, 0x2a, 0xa3, 0xd8, 0x4d, 0x48, 0xcb, 0x3a, 0x82, 0xec,
	0x53, 0x84, 0xea, 0xb3, 0x48, 0x63, 0xc5, 0x80, 0x4f, 0x93, 0x82, 0x50, 0x84, 0x32, 0xd9, 0xb9,
	0xd9, 0x2e, 0xb4, 0x33, 0x71, 0x66, 0x12, 0xe8, 0x2f, 0xf1, 0x97, 0xf8, 0xff, 0x64, 0x67, 0x77,
	0xed, 0x6c, 0x9b, 0x16, 0x41, 0xdf, 0xf6, 0x9e, 0x39, 0xf7, 0x9e, 0x73, 0x3f, 0x12, 0x78, 0x6e,
	0x94, 0xcc, 0x2f, 0x04, 0xb7, 0x7c, 0xc9, 0x0d, 0x4e, 0xd7, 0x5a, 0x59, 0x45, 0x86, 0x0b, 0x5c,
	0xaf, 0xd5, 0x02, 0xf5, 0xb6, 0xc8, 0x70, 0x7c, 0xd8, 0xa2, 0x5c, 0x6c, 0xb9, 0x2e, 0xb8, 0x2d,
	0x94, 0xac, 0xc8, 0xf4, 0x2b, 0x0c, 0x17, 0x4a, 0xe6, 0x9f, 0xea, 0x77, 0xb2, 0x0f, 0x9d, 0x42,
	0xc4, 0x41, 0x12, 0xa4, 0x11, 0xeb, 0x14, 0x82, 0x10, 0x08, 0x25, 0xbf, 0xc6, 0xb8, 0x93, 0x04,
	0xe9, 0x1e, 0x73, 0xdf, 0x24, 0x86, 0x27, 0x5b, 0xd4, 0xa6, 0x50, 0x32, 0xee, 0x26, 0x41, 0x1a,
	0xb2, 0x26, 0xa4, 0xe7, 0xf0, 0xcc, 0xaf, 0x76, 0x2a, 0x72, 0x24, 0x53, 0x08, 0xa5, 0x12, 0xe8,
	0x6a, 0x0e, 0x8e, 0xc7, 0x53, 0xdf, 0xdd, 0xd4, 0x67, 0x33, 0xc7, 0x23, 0x2f, 0xa1, 0x9f, 0x6d,
	0xb4, 0x51, 0xda, 0x69, 0x46, 0xac, 0x8e, 0xa8, 0x82, 0x03, 0x9f, 0x6d, 0x66, 0x4a, 0x4a, 0xcc,
	0xca, 0x56, 0xc8, 0x7b, 0xe8, 0xa1, 0xc8, 0xd1, 0xc4, 0x41, 0xd2, 0x4d, 0x07, 0xc7, 0x47, 0x0f,
	0x6b, 0x94, 0x8e, 0x58, 0x45, 0x26, 0x47, 0x00, 0x56, 0x59, 0x7e, 0x35, 0x53, 0x1b, 0x69, 0x5d,
	0x27, 0x11, 0xf3, 0x10, 0xfa, 0x2b, 0x80, 0xd1, 0x67, 0xb4, 0xd9, 0x65, 0x4b, 0x96, 0xe1, 0x8f,
	0x0d, 0x1a, 0x4b, 0x5e, 0x40, 0x8f, 0xaf, 0x2c, 0xea, 0x7a, 0x56, 0x55, 0x50, 0x9a, 0x5f, 0xe2,
	0x4a, 0x69, 0x6c, 0xcc, 0x57, 0x51, 0xc9, 0x5e, 0x15, 0xda, 0x34, 0x32, 0x55, 0x50, 0x0e, 0xf7,
	0x8a, 0x1b, 0x1b, 0x87, 0x0e, 0x74, 0xdf, 0xa5, 0x2b, 0x83, 0x5c, 0x67, 0x97, 0xdf, 0x94, 0x16,
	0x71, 0xcf, 0x8d, 0xdd, 0x43, 0x48, 0x02, 0x83, 0x3f, 0x3b, 0x9c, 0x8b, 0xb8, 0xef, 0x52, 0x7d,
	0x88, 0x7e, 0x81, 0xc9, 0x3d, 0xdb, 0x27, 0x37, 0x73, 0xd1, 0x38, 0x4f, 0xe1, 0xa9, 0xf1, 0x9e,
	0xe6, 0xa2, 0x9a, 0x5b, 0xc4, 0xee, 0xc2, 0x94, 0xc3, 0xe1, 0x03, 0x95, 0xcc, 0x5a, 0x49, 0x83,
	0xe4, 0x23, 0x44, 0x7e, 0x4e, 0xb3, 0x80, 0xc7, 0x96, 0xdc, 0x4e, 0xa0, 0x14, 0x12, 0x27, 0x71,
	0xc6, 0x73, 0x73, 0x72, 0xb3, 0x68, 0x19, 0xa8, 0x0d, 0xd3, 0xd7, 0xf0, 0xea, 0x11, 0x4e, 0x65,
	0x85, 0xbe, 0x85, 0xd1, 0x4c, 0x23, 0xb7, 0xd8, 0x52, 0xab, 0x5b, 0x6e, 0xae, 0x38, 0xb8, 0xbd,
	0x62, 0xfa, 0x1d, 0xc6, 0xbb, 0x12, 0xea, 0xce, 0x3e, 0xc0, 0xd0, 0x37, 0xfa, 0x17, 0xd7, 0xdb,
	0xe2, 0xd3, 0x9f, 0x01, 0x1c, 0x9c, 0x8a, 0xc2, 0xee, 0x72, 0xf3, 0x06, 0xf6, 0xdb, 0x93, 0xae,
	0x6f, 0xe8, 0x0e, 0xba, 0xf3, 0xb7, 0x37, 0x81, 0x3d, 0x2e, 0xc4, 0x19, 0xcf, 0xcb, 0xb5, 0x75,
	0xdd, 0xda, 0x6e, 0x01, 0x42, 0x61, 0xa8, 0xf1, 0x5a, 0x6d, 0xb1, 0x26, 0x84, 0x8e, 0xd0, 0xc2,
	0xe8, 0x39, 0xc4, 0xf7, 0x8d, 0xfd, 0xa7, 0xae, 0x67, 0x30, 0x62, 0x4e, 0xeb, 0x1f, 0xda, 0xa6,
	0x13, 0x18, 0xef, 0x2a, 0x52, 0x59, 0x5c, 0xf6, 0xdd, 0xff, 0xd6, 0xbb, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x5e, 0x3f, 0x3c, 0x40, 0xfb, 0x04, 0x00, 0x00,
}
