// Code generated by protoc-gen-go.
// source: variation_version.proto
// DO NOT EDIT!

package SeppoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type VariationVersion struct {
	Id          uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	VariationId uint64 `protobuf:"varint,2,opt,name=variationId" json:"variationId,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Text        string `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Version     uint32 `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	CreatedAt   int64  `protobuf:"varint,6,opt,name=createdAt" json:"createdAt,omitempty"`
	DisabledAt  int64  `protobuf:"varint,7,opt,name=disabledAt" json:"disabledAt,omitempty"`
}

func (m *VariationVersion) Reset()                    { *m = VariationVersion{} }
func (m *VariationVersion) String() string            { return proto.CompactTextString(m) }
func (*VariationVersion) ProtoMessage()               {}
func (*VariationVersion) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *VariationVersion) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VariationVersion) GetVariationId() uint64 {
	if m != nil {
		return m.VariationId
	}
	return 0
}

func (m *VariationVersion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VariationVersion) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *VariationVersion) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VariationVersion) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *VariationVersion) GetDisabledAt() int64 {
	if m != nil {
		return m.DisabledAt
	}
	return 0
}

type FetchNewestVariationVersionByVariationIdRequest struct {
	VariationIds []uint64 `protobuf:"varint,1,rep,packed,name=variationIds" json:"variationIds,omitempty"`
}

func (m *FetchNewestVariationVersionByVariationIdRequest) Reset() {
	*m = FetchNewestVariationVersionByVariationIdRequest{}
}
func (m *FetchNewestVariationVersionByVariationIdRequest) String() string {
	return proto.CompactTextString(m)
}
func (*FetchNewestVariationVersionByVariationIdRequest) ProtoMessage() {}
func (*FetchNewestVariationVersionByVariationIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{1}
}

func (m *FetchNewestVariationVersionByVariationIdRequest) GetVariationIds() []uint64 {
	if m != nil {
		return m.VariationIds
	}
	return nil
}

type FetchNewestVariationVersionByVariationIdResponse struct {
	VariationVersions []*VariationVersion `protobuf:"bytes,1,rep,name=variationVersions" json:"variationVersions,omitempty"`
}

func (m *FetchNewestVariationVersionByVariationIdResponse) Reset() {
	*m = FetchNewestVariationVersionByVariationIdResponse{}
}
func (m *FetchNewestVariationVersionByVariationIdResponse) String() string {
	return proto.CompactTextString(m)
}
func (*FetchNewestVariationVersionByVariationIdResponse) ProtoMessage() {}
func (*FetchNewestVariationVersionByVariationIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{2}
}

func (m *FetchNewestVariationVersionByVariationIdResponse) GetVariationVersions() []*VariationVersion {
	if m != nil {
		return m.VariationVersions
	}
	return nil
}

type FetchVariationVersionByIdRequest struct {
	VariationVersionIds []uint64 `protobuf:"varint,1,rep,packed,name=variationVersionIds" json:"variationVersionIds,omitempty"`
}

func (m *FetchVariationVersionByIdRequest) Reset()         { *m = FetchVariationVersionByIdRequest{} }
func (m *FetchVariationVersionByIdRequest) String() string { return proto.CompactTextString(m) }
func (*FetchVariationVersionByIdRequest) ProtoMessage()    {}
func (*FetchVariationVersionByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{3}
}

func (m *FetchVariationVersionByIdRequest) GetVariationVersionIds() []uint64 {
	if m != nil {
		return m.VariationVersionIds
	}
	return nil
}

type FetchVariationVersionByIdResponse struct {
	VariationVersions []*VariationVersion `protobuf:"bytes,1,rep,name=variationVersions" json:"variationVersions,omitempty"`
}

func (m *FetchVariationVersionByIdResponse) Reset()         { *m = FetchVariationVersionByIdResponse{} }
func (m *FetchVariationVersionByIdResponse) String() string { return proto.CompactTextString(m) }
func (*FetchVariationVersionByIdResponse) ProtoMessage()    {}
func (*FetchVariationVersionByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor12, []int{4}
}

func (m *FetchVariationVersionByIdResponse) GetVariationVersions() []*VariationVersion {
	if m != nil {
		return m.VariationVersions
	}
	return nil
}

func init() {
	proto.RegisterType((*VariationVersion)(nil), "SeppoService.VariationVersion")
	proto.RegisterType((*FetchNewestVariationVersionByVariationIdRequest)(nil), "SeppoService.FetchNewestVariationVersionByVariationIdRequest")
	proto.RegisterType((*FetchNewestVariationVersionByVariationIdResponse)(nil), "SeppoService.FetchNewestVariationVersionByVariationIdResponse")
	proto.RegisterType((*FetchVariationVersionByIdRequest)(nil), "SeppoService.FetchVariationVersionByIdRequest")
	proto.RegisterType((*FetchVariationVersionByIdResponse)(nil), "SeppoService.FetchVariationVersionByIdResponse")
}

func init() { proto.RegisterFile("variation_version.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x24, 0xb4, 0xea, 0xb5, 0x20, 0x30, 0x03, 0x1e, 0x50, 0x65, 0x3c, 0x65, 0x0a,
	0x15, 0x3c, 0x01, 0x0c, 0x48, 0x48, 0x88, 0xc1, 0x85, 0xac, 0x28, 0x4d, 0x4e, 0xc2, 0x12, 0xc4,
	0xa9, 0x6d, 0x02, 0x6c, 0x3c, 0x1c, 0x0f, 0x86, 0xea, 0x50, 0x12, 0x52, 0x84, 0x58, 0xd8, 0xce,
	0xdf, 0x7f, 0xf7, 0xfb, 0x7e, 0xcb, 0x70, 0x50, 0x67, 0x46, 0x65, 0x4e, 0xe9, 0xf2, 0xae, 0x46,
	0x63, 0x95, 0x2e, 0x93, 0xca, 0x68, 0xa7, 0xe9, 0x64, 0x8e, 0x55, 0xa5, 0xe7, 0x68, 0x6a, 0x95,
	0xa3, 0x78, 0x27, 0xb0, 0x9b, 0xae, 0x3b, 0xd3, 0xa6, 0x91, 0xee, 0x40, 0xa0, 0x0a, 0x46, 0x38,
	0x89, 0x23, 0x19, 0xa8, 0x82, 0x72, 0x18, 0x7f, 0xb9, 0x5d, 0x16, 0x2c, 0xf0, 0x42, 0x17, 0x51,
	0x0a, 0x51, 0x99, 0x3d, 0x22, 0x0b, 0x39, 0x89, 0x47, 0xd2, 0xd7, 0x2b, 0xe6, 0xf0, 0xc5, 0xb1,
	0xa8, 0x61, 0xab, 0x9a, 0x32, 0x18, 0x7e, 0x6e, 0xc3, 0xb6, 0x38, 0x89, 0xb7, 0xe5, 0xfa, 0x48,
	0x0f, 0x61, 0x94, 0x1b, 0xcc, 0x1c, 0x16, 0x67, 0x8e, 0x0d, 0x38, 0x89, 0x43, 0xd9, 0x02, 0x3a,
	0x05, 0x28, 0x94, 0xcd, 0x16, 0x0f, 0x5e, 0x1e, 0x7a, 0xb9, 0x43, 0xc4, 0x2d, 0x1c, 0x5f, 0xa0,
	0xcb, 0xef, 0xaf, 0xf1, 0x19, 0xad, 0xeb, 0x07, 0x3a, 0x7f, 0x4d, 0xdb, 0x5d, 0x25, 0x2e, 0x9f,
	0xd0, 0x3a, 0x2a, 0x60, 0xd2, 0x49, 0x60, 0x19, 0xe1, 0x61, 0x1c, 0xc9, 0x6f, 0x4c, 0xbc, 0x11,
	0x98, 0xfd, 0xdd, 0xd7, 0x56, 0xba, 0xb4, 0x48, 0xaf, 0x60, 0xaf, 0xee, 0x35, 0x36, 0xee, 0xe3,
	0x93, 0x69, 0xd2, 0x7d, 0xfc, 0xa4, 0xef, 0x27, 0x37, 0x07, 0xc5, 0x0d, 0x70, 0xbf, 0xc1, 0xe6,
	0xdd, 0x6d, 0x94, 0x19, 0xec, 0xf7, 0x07, 0xdb, 0x44, 0x3f, 0x49, 0x62, 0x09, 0x47, 0xbf, 0xb8,
	0xfe, 0x47, 0x90, 0xc5, 0xc0, 0x7f, 0xbf, 0xd3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x66,
	0x7d, 0xe2, 0x99, 0x02, 0x00, 0x00,
}
