// Code generated by protoc-gen-go.
// source: ew_database.proto
// DO NOT EDIT!

/*
Package MatiasService is a generated protocol buffer package.

It is generated from these files:
	ew_database.proto
	matias_service.proto

It has these top-level messages:
	EwSong
	VariationIdEwSongId
	NewSongId
	InsertEwSongIdsRequest
	InsertEwSongIdsResponse
	SyncEwDatabaseRequest
	SyncEwDatabaseResponse
	SyncEwSongRequest
	SyncEwSongResponse
	RequestEwDatabaseChangesRequest
	EwDatabaseChange
	RequestMatiasKeyRequest
	RequestMatiasKeyResponse
*/
package MatiasService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EwDatabaseChangeType int32

const (
	EwDatabaseChangeType_NEW_SONG    EwDatabaseChangeType = 0
	EwDatabaseChangeType_REMOVE_SONG EwDatabaseChangeType = 1
)

var EwDatabaseChangeType_name = map[int32]string{
	0: "NEW_SONG",
	1: "REMOVE_SONG",
}
var EwDatabaseChangeType_value = map[string]int32{
	"NEW_SONG":    0,
	"REMOVE_SONG": 1,
}

func (x EwDatabaseChangeType) String() string {
	return proto.EnumName(EwDatabaseChangeType_name, int32(x))
}
func (EwDatabaseChangeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EwSong struct {
	Id            uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Author        string `protobuf:"bytes,3,opt,name=author" json:"author,omitempty"`
	Copyright     string `protobuf:"bytes,4,opt,name=copyright" json:"copyright,omitempty"`
	Administrator string `protobuf:"bytes,5,opt,name=administrator" json:"administrator,omitempty"`
	Description   string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Tags          string `protobuf:"bytes,7,opt,name=tags" json:"tags,omitempty"`
	Text          string `protobuf:"bytes,8,opt,name=text" json:"text,omitempty"`
	VariationId   uint32 `protobuf:"varint,9,opt,name=variationId" json:"variationId,omitempty"`
}

func (m *EwSong) Reset()                    { *m = EwSong{} }
func (m *EwSong) String() string            { return proto.CompactTextString(m) }
func (*EwSong) ProtoMessage()               {}
func (*EwSong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EwSong) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EwSong) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EwSong) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *EwSong) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

func (m *EwSong) GetAdministrator() string {
	if m != nil {
		return m.Administrator
	}
	return ""
}

func (m *EwSong) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EwSong) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *EwSong) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EwSong) GetVariationId() uint32 {
	if m != nil {
		return m.VariationId
	}
	return 0
}

type VariationIdEwSongId struct {
	EwSongId    uint32 `protobuf:"varint,1,opt,name=ewSongId" json:"ewSongId,omitempty"`
	VariationId uint32 `protobuf:"varint,2,opt,name=variationId" json:"variationId,omitempty"`
}

func (m *VariationIdEwSongId) Reset()                    { *m = VariationIdEwSongId{} }
func (m *VariationIdEwSongId) String() string            { return proto.CompactTextString(m) }
func (*VariationIdEwSongId) ProtoMessage()               {}
func (*VariationIdEwSongId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VariationIdEwSongId) GetEwSongId() uint32 {
	if m != nil {
		return m.EwSongId
	}
	return 0
}

func (m *VariationIdEwSongId) GetVariationId() uint32 {
	if m != nil {
		return m.VariationId
	}
	return 0
}

type NewSongId struct {
	OldEwSongId uint32 `protobuf:"varint,1,opt,name=oldEwSongId" json:"oldEwSongId,omitempty"`
	NewEwSongId uint32 `protobuf:"varint,2,opt,name=newEwSongId" json:"newEwSongId,omitempty"`
}

func (m *NewSongId) Reset()                    { *m = NewSongId{} }
func (m *NewSongId) String() string            { return proto.CompactTextString(m) }
func (*NewSongId) ProtoMessage()               {}
func (*NewSongId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NewSongId) GetOldEwSongId() uint32 {
	if m != nil {
		return m.OldEwSongId
	}
	return 0
}

func (m *NewSongId) GetNewEwSongId() uint32 {
	if m != nil {
		return m.NewEwSongId
	}
	return 0
}

type InsertEwSongIdsRequest struct {
	EwDatabaseKey        string                 `protobuf:"bytes,1,opt,name=ewDatabaseKey" json:"ewDatabaseKey,omitempty"`
	VariationIdEwSongIds []*VariationIdEwSongId `protobuf:"bytes,2,rep,name=variationIdEwSongIds" json:"variationIdEwSongIds,omitempty"`
	NewSongIds           []*NewSongId           `protobuf:"bytes,3,rep,name=newSongIds" json:"newSongIds,omitempty"`
}

func (m *InsertEwSongIdsRequest) Reset()                    { *m = InsertEwSongIdsRequest{} }
func (m *InsertEwSongIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*InsertEwSongIdsRequest) ProtoMessage()               {}
func (*InsertEwSongIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InsertEwSongIdsRequest) GetEwDatabaseKey() string {
	if m != nil {
		return m.EwDatabaseKey
	}
	return ""
}

func (m *InsertEwSongIdsRequest) GetVariationIdEwSongIds() []*VariationIdEwSongId {
	if m != nil {
		return m.VariationIdEwSongIds
	}
	return nil
}

func (m *InsertEwSongIdsRequest) GetNewSongIds() []*NewSongId {
	if m != nil {
		return m.NewSongIds
	}
	return nil
}

type InsertEwSongIdsResponse struct {
}

func (m *InsertEwSongIdsResponse) Reset()                    { *m = InsertEwSongIdsResponse{} }
func (m *InsertEwSongIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*InsertEwSongIdsResponse) ProtoMessage()               {}
func (*InsertEwSongIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SyncEwDatabaseRequest struct {
	EwDatabaseKey string    `protobuf:"bytes,1,opt,name=ewDatabaseKey" json:"ewDatabaseKey,omitempty"`
	EwSongs       []*EwSong `protobuf:"bytes,2,rep,name=ewSongs" json:"ewSongs,omitempty"`
}

func (m *SyncEwDatabaseRequest) Reset()                    { *m = SyncEwDatabaseRequest{} }
func (m *SyncEwDatabaseRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncEwDatabaseRequest) ProtoMessage()               {}
func (*SyncEwDatabaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SyncEwDatabaseRequest) GetEwDatabaseKey() string {
	if m != nil {
		return m.EwDatabaseKey
	}
	return ""
}

func (m *SyncEwDatabaseRequest) GetEwSongs() []*EwSong {
	if m != nil {
		return m.EwSongs
	}
	return nil
}

type SyncEwDatabaseResponse struct {
	EwSongs         []*EwSong `protobuf:"bytes,1,rep,name=ewSongs" json:"ewSongs,omitempty"`
	RemoveEwSongIds []uint32  `protobuf:"varint,2,rep,packed,name=removeEwSongIds" json:"removeEwSongIds,omitempty"`
	EwDatabaseFound bool      `protobuf:"varint,3,opt,name=ewDatabaseFound" json:"ewDatabaseFound,omitempty"`
}

func (m *SyncEwDatabaseResponse) Reset()                    { *m = SyncEwDatabaseResponse{} }
func (m *SyncEwDatabaseResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncEwDatabaseResponse) ProtoMessage()               {}
func (*SyncEwDatabaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SyncEwDatabaseResponse) GetEwSongs() []*EwSong {
	if m != nil {
		return m.EwSongs
	}
	return nil
}

func (m *SyncEwDatabaseResponse) GetRemoveEwSongIds() []uint32 {
	if m != nil {
		return m.RemoveEwSongIds
	}
	return nil
}

func (m *SyncEwDatabaseResponse) GetEwDatabaseFound() bool {
	if m != nil {
		return m.EwDatabaseFound
	}
	return false
}

type SyncEwSongRequest struct {
	EwDatabaseKey string  `protobuf:"bytes,1,opt,name=ewDatabaseKey" json:"ewDatabaseKey,omitempty"`
	EwSong        *EwSong `protobuf:"bytes,2,opt,name=ewSong" json:"ewSong,omitempty"`
}

func (m *SyncEwSongRequest) Reset()                    { *m = SyncEwSongRequest{} }
func (m *SyncEwSongRequest) String() string            { return proto.CompactTextString(m) }
func (*SyncEwSongRequest) ProtoMessage()               {}
func (*SyncEwSongRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SyncEwSongRequest) GetEwDatabaseKey() string {
	if m != nil {
		return m.EwDatabaseKey
	}
	return ""
}

func (m *SyncEwSongRequest) GetEwSong() *EwSong {
	if m != nil {
		return m.EwSong
	}
	return nil
}

type SyncEwSongResponse struct {
	EwSongId uint32 `protobuf:"varint,1,opt,name=ewSongId" json:"ewSongId,omitempty"`
	Success  bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *SyncEwSongResponse) Reset()                    { *m = SyncEwSongResponse{} }
func (m *SyncEwSongResponse) String() string            { return proto.CompactTextString(m) }
func (*SyncEwSongResponse) ProtoMessage()               {}
func (*SyncEwSongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SyncEwSongResponse) GetEwSongId() uint32 {
	if m != nil {
		return m.EwSongId
	}
	return 0
}

func (m *SyncEwSongResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RequestEwDatabaseChangesRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *RequestEwDatabaseChangesRequest) Reset()                    { *m = RequestEwDatabaseChangesRequest{} }
func (m *RequestEwDatabaseChangesRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestEwDatabaseChangesRequest) ProtoMessage()               {}
func (*RequestEwDatabaseChangesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RequestEwDatabaseChangesRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type EwDatabaseChange struct {
	ChangeType   EwDatabaseChangeType `protobuf:"varint,1,opt,name=changeType,enum=MatiasService.EwDatabaseChangeType" json:"changeType,omitempty"`
	RemoveSongId uint32               `protobuf:"varint,2,opt,name=removeSongId" json:"removeSongId,omitempty"`
	EwSong       *EwSong              `protobuf:"bytes,3,opt,name=ewSong" json:"ewSong,omitempty"`
}

func (m *EwDatabaseChange) Reset()                    { *m = EwDatabaseChange{} }
func (m *EwDatabaseChange) String() string            { return proto.CompactTextString(m) }
func (*EwDatabaseChange) ProtoMessage()               {}
func (*EwDatabaseChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EwDatabaseChange) GetChangeType() EwDatabaseChangeType {
	if m != nil {
		return m.ChangeType
	}
	return EwDatabaseChangeType_NEW_SONG
}

func (m *EwDatabaseChange) GetRemoveSongId() uint32 {
	if m != nil {
		return m.RemoveSongId
	}
	return 0
}

func (m *EwDatabaseChange) GetEwSong() *EwSong {
	if m != nil {
		return m.EwSong
	}
	return nil
}

func init() {
	proto.RegisterType((*EwSong)(nil), "MatiasService.EwSong")
	proto.RegisterType((*VariationIdEwSongId)(nil), "MatiasService.VariationIdEwSongId")
	proto.RegisterType((*NewSongId)(nil), "MatiasService.NewSongId")
	proto.RegisterType((*InsertEwSongIdsRequest)(nil), "MatiasService.InsertEwSongIdsRequest")
	proto.RegisterType((*InsertEwSongIdsResponse)(nil), "MatiasService.InsertEwSongIdsResponse")
	proto.RegisterType((*SyncEwDatabaseRequest)(nil), "MatiasService.SyncEwDatabaseRequest")
	proto.RegisterType((*SyncEwDatabaseResponse)(nil), "MatiasService.SyncEwDatabaseResponse")
	proto.RegisterType((*SyncEwSongRequest)(nil), "MatiasService.SyncEwSongRequest")
	proto.RegisterType((*SyncEwSongResponse)(nil), "MatiasService.SyncEwSongResponse")
	proto.RegisterType((*RequestEwDatabaseChangesRequest)(nil), "MatiasService.RequestEwDatabaseChangesRequest")
	proto.RegisterType((*EwDatabaseChange)(nil), "MatiasService.EwDatabaseChange")
	proto.RegisterEnum("MatiasService.EwDatabaseChangeType", EwDatabaseChangeType_name, EwDatabaseChangeType_value)
}

func init() { proto.RegisterFile("ew_database.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0xed, 0xd6, 0xb5, 0x77, 0xeb, 0x3e, 0x4c, 0x57, 0x0c, 0x42, 0xa2, 0x32, 0x3c, 0x54,
	0x48, 0x14, 0x69, 0x13, 0x12, 0xef, 0xa3, 0xa0, 0x82, 0xd6, 0x4a, 0x2e, 0x2a, 0x8f, 0x93, 0x97,
	0x5c, 0xb5, 0x16, 0x9b, 0x5d, 0x62, 0xb7, 0x5d, 0x7f, 0x0c, 0x7f, 0x80, 0x5f, 0xc3, 0xaf, 0xe1,
	0x19, 0xc5, 0x49, 0xd3, 0x24, 0x2d, 0x68, 0x7b, 0xf3, 0x3d, 0x39, 0x3e, 0xf7, 0xdc, 0x63, 0x3b,
	0x70, 0x82, 0x8b, 0xab, 0x40, 0x58, 0x71, 0x2d, 0x0c, 0x76, 0xa6, 0xa1, 0xb6, 0x9a, 0xd4, 0x2f,
	0x85, 0x95, 0xc2, 0x0c, 0x31, 0x9c, 0x4b, 0x1f, 0xd9, 0x1f, 0x0f, 0x2a, 0xdd, 0xc5, 0x50, 0xab,
	0x31, 0x39, 0x84, 0x92, 0x0c, 0xa8, 0xd7, 0xf2, 0xda, 0x75, 0x5e, 0x92, 0x01, 0x69, 0xc0, 0xae,
	0x95, 0xf6, 0x06, 0x69, 0xa9, 0xe5, 0xb5, 0x6b, 0x3c, 0x2e, 0x48, 0x13, 0x2a, 0x62, 0x66, 0x27,
	0x3a, 0xa4, 0x65, 0x07, 0x27, 0x15, 0x79, 0x0e, 0x35, 0x5f, 0x4f, 0x97, 0xa1, 0x1c, 0x4f, 0x2c,
	0xdd, 0x71, 0x9f, 0xd6, 0x00, 0x79, 0x05, 0x75, 0x11, 0xdc, 0x4a, 0x25, 0x8d, 0x0d, 0x85, 0xd5,
	0x21, 0xdd, 0x75, 0x8c, 0x3c, 0x48, 0x5a, 0xb0, 0x1f, 0xa0, 0xf1, 0x43, 0x39, 0xb5, 0x52, 0x2b,
	0x5a, 0x71, 0x9c, 0x2c, 0x44, 0x08, 0xec, 0x58, 0x31, 0x36, 0x74, 0xcf, 0x7d, 0x72, 0x6b, 0x87,
	0xe1, 0x9d, 0xa5, 0xd5, 0x04, 0xc3, 0x3b, 0x1b, 0x29, 0xcd, 0x45, 0x28, 0x45, 0xb4, 0xa9, 0x17,
	0xd0, 0x9a, 0x1b, 0x2a, 0x0b, 0xb1, 0x21, 0x3c, 0x1e, 0xad, 0xcb, 0x38, 0x82, 0x5e, 0x40, 0x9e,
	0x41, 0x15, 0x93, 0x75, 0x12, 0x45, 0x5a, 0x17, 0x45, 0x4b, 0x9b, 0xa2, 0x03, 0xa8, 0xf5, 0xb3,
	0x74, 0x7d, 0x93, 0x2a, 0x27, 0x6a, 0x59, 0x28, 0x62, 0x28, 0x5c, 0xa4, 0x8c, 0x44, 0x30, 0x03,
	0xb1, 0xdf, 0x1e, 0x34, 0x7b, 0xca, 0x60, 0x68, 0x57, 0x90, 0xe1, 0xf8, 0x63, 0x86, 0xc6, 0x45,
	0x8a, 0x8b, 0x0f, 0xc9, 0xe1, 0x7e, 0xc1, 0xa5, 0x6b, 0x50, 0xe3, 0x79, 0x90, 0x8c, 0xa0, 0x31,
	0xdf, 0x1c, 0xd3, 0xd0, 0x52, 0xab, 0xdc, 0xde, 0x3f, 0x63, 0x9d, 0xdc, 0x6d, 0xe8, 0x6c, 0x49,
	0x84, 0x6f, 0xdd, 0x4f, 0xde, 0x03, 0x28, 0x4c, 0xd5, 0xca, 0x4e, 0x8d, 0x16, 0xd4, 0xd2, 0x28,
	0x78, 0x86, 0xcb, 0x9e, 0xc2, 0x93, 0x8d, 0x89, 0xcc, 0x54, 0x2b, 0x83, 0x4c, 0xc1, 0xe9, 0x70,
	0xa9, 0xfc, 0x6e, 0x3a, 0xc1, 0xc3, 0x66, 0x7d, 0x0b, 0x7b, 0x71, 0x9b, 0xd5, 0x78, 0xa7, 0x05,
	0x43, 0x71, 0x47, 0xbe, 0x62, 0xb1, 0x9f, 0x1e, 0x34, 0x8b, 0x0d, 0x63, 0x2b, 0x59, 0x2d, 0xef,
	0x3e, 0x5a, 0xa4, 0x0d, 0x47, 0x21, 0xde, 0xea, 0x39, 0xe6, 0x33, 0xae, 0xf3, 0x22, 0x1c, 0x31,
	0xd7, 0xbe, 0x3f, 0xea, 0x99, 0x0a, 0xdc, 0x53, 0xaa, 0xf2, 0x22, 0xcc, 0x26, 0x70, 0x12, 0xdb,
	0x73, 0xad, 0x1e, 0x94, 0xc5, 0x1b, 0xa8, 0xc4, 0xce, 0xdc, 0xad, 0xfa, 0xa7, 0xfd, 0x84, 0xc4,
	0x3e, 0x03, 0xc9, 0x76, 0x4a, 0x42, 0xf8, 0xdf, 0x63, 0xa0, 0xb0, 0x67, 0x66, 0xbe, 0x8f, 0xc6,
	0xb8, 0x0e, 0x55, 0xbe, 0x2a, 0xd9, 0x39, 0xbc, 0x48, 0xbc, 0xae, 0x73, 0xbd, 0x98, 0x08, 0x35,
	0xc6, 0xf4, 0xee, 0x1e, 0x43, 0xf9, 0x7b, 0xea, 0x3c, 0x5a, 0xb2, 0x5f, 0x1e, 0x1c, 0x17, 0xe9,
	0xe4, 0x02, 0xc0, 0x77, 0xab, 0xaf, 0xcb, 0x29, 0x3a, 0xf6, 0xe1, 0xd9, 0xcb, 0x8d, 0x41, 0xf2,
	0x9b, 0x22, 0x2a, 0xcf, 0x6c, 0x23, 0x0c, 0x0e, 0xe2, 0x13, 0xc8, 0xbd, 0xb2, 0x1c, 0x96, 0x49,
	0xab, 0x7c, 0x8f, 0xb4, 0x5e, 0xbf, 0x83, 0xc6, 0xb6, 0xb6, 0xe4, 0x00, 0xaa, 0xfd, 0xee, 0xb7,
	0xab, 0xe1, 0xa0, 0xff, 0xe9, 0xf8, 0x11, 0x39, 0x82, 0x7d, 0xde, 0xbd, 0x1c, 0x8c, 0xba, 0x31,
	0xe0, 0x5d, 0x57, 0xdc, 0x1f, 0xf8, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x05, 0xb2,
	0xfd, 0x96, 0x05, 0x00, 0x00,
}
