// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// SRUpdatedEwDatabaseLinkVersion is an object representing the database table.
type SRUpdatedEwDatabaseLinkVersion struct {
	ID             uint64 `boil:"id" json:"id" toml:"id" yaml:"id"`
	SRID           uint64 `boil:"sr_id" json:"sr_id" toml:"sr_id" yaml:"sr_id"`
	OrigVersion    uint   `boil:"orig_version" json:"orig_version" toml:"orig_version" yaml:"orig_version"`
	ChangedVersion uint   `boil:"changed_version" json:"changed_version" toml:"changed_version" yaml:"changed_version"`
	VariationID    uint64 `boil:"variation_id" json:"variation_id" toml:"variation_id" yaml:"variation_id"`

	R *srUpdatedEwDatabaseLinkVersionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L srUpdatedEwDatabaseLinkVersionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SRUpdatedEwDatabaseLinkVersionColumns = struct {
	ID             string
	SRID           string
	OrigVersion    string
	ChangedVersion string
	VariationID    string
}{
	ID:             "id",
	SRID:           "sr_id",
	OrigVersion:    "orig_version",
	ChangedVersion: "changed_version",
	VariationID:    "variation_id",
}

// srUpdatedEwDatabaseLinkVersionR is where relationships are stored.
type srUpdatedEwDatabaseLinkVersionR struct {
	SR        *SynchronizationRaport
	Variation *Variation
}

// srUpdatedEwDatabaseLinkVersionL is where Load methods for each relationship are stored.
type srUpdatedEwDatabaseLinkVersionL struct{}

var (
	srUpdatedEwDatabaseLinkVersionColumns               = []string{"id", "sr_id", "orig_version", "changed_version", "variation_id"}
	srUpdatedEwDatabaseLinkVersionColumnsWithoutDefault = []string{"sr_id", "orig_version", "changed_version", "variation_id"}
	srUpdatedEwDatabaseLinkVersionColumnsWithDefault    = []string{"id"}
	srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns     = []string{"id"}
)

type (
	// SRUpdatedEwDatabaseLinkVersionSlice is an alias for a slice of pointers to SRUpdatedEwDatabaseLinkVersion.
	// This should generally be used opposed to []SRUpdatedEwDatabaseLinkVersion.
	SRUpdatedEwDatabaseLinkVersionSlice []*SRUpdatedEwDatabaseLinkVersion
	// SRUpdatedEwDatabaseLinkVersionHook is the signature for custom SRUpdatedEwDatabaseLinkVersion hook methods
	SRUpdatedEwDatabaseLinkVersionHook func(boil.Executor, *SRUpdatedEwDatabaseLinkVersion) error

	srUpdatedEwDatabaseLinkVersionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	srUpdatedEwDatabaseLinkVersionType                 = reflect.TypeOf(&SRUpdatedEwDatabaseLinkVersion{})
	srUpdatedEwDatabaseLinkVersionMapping              = queries.MakeStructMapping(srUpdatedEwDatabaseLinkVersionType)
	srUpdatedEwDatabaseLinkVersionPrimaryKeyMapping, _ = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns)
	srUpdatedEwDatabaseLinkVersionInsertCacheMut       sync.RWMutex
	srUpdatedEwDatabaseLinkVersionInsertCache          = make(map[string]insertCache)
	srUpdatedEwDatabaseLinkVersionUpdateCacheMut       sync.RWMutex
	srUpdatedEwDatabaseLinkVersionUpdateCache          = make(map[string]updateCache)
	srUpdatedEwDatabaseLinkVersionUpsertCacheMut       sync.RWMutex
	srUpdatedEwDatabaseLinkVersionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var srUpdatedEwDatabaseLinkVersionBeforeInsertHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionBeforeUpdateHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionBeforeDeleteHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionBeforeUpsertHooks []SRUpdatedEwDatabaseLinkVersionHook

var srUpdatedEwDatabaseLinkVersionAfterInsertHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionAfterSelectHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionAfterUpdateHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionAfterDeleteHooks []SRUpdatedEwDatabaseLinkVersionHook
var srUpdatedEwDatabaseLinkVersionAfterUpsertHooks []SRUpdatedEwDatabaseLinkVersionHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *SRUpdatedEwDatabaseLinkVersion) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range srUpdatedEwDatabaseLinkVersionAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSRUpdatedEwDatabaseLinkVersionHook registers your hook function for all future operations.
func AddSRUpdatedEwDatabaseLinkVersionHook(hookPoint boil.HookPoint, srUpdatedEwDatabaseLinkVersionHook SRUpdatedEwDatabaseLinkVersionHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		srUpdatedEwDatabaseLinkVersionBeforeInsertHooks = append(srUpdatedEwDatabaseLinkVersionBeforeInsertHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.BeforeUpdateHook:
		srUpdatedEwDatabaseLinkVersionBeforeUpdateHooks = append(srUpdatedEwDatabaseLinkVersionBeforeUpdateHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.BeforeDeleteHook:
		srUpdatedEwDatabaseLinkVersionBeforeDeleteHooks = append(srUpdatedEwDatabaseLinkVersionBeforeDeleteHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.BeforeUpsertHook:
		srUpdatedEwDatabaseLinkVersionBeforeUpsertHooks = append(srUpdatedEwDatabaseLinkVersionBeforeUpsertHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.AfterInsertHook:
		srUpdatedEwDatabaseLinkVersionAfterInsertHooks = append(srUpdatedEwDatabaseLinkVersionAfterInsertHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.AfterSelectHook:
		srUpdatedEwDatabaseLinkVersionAfterSelectHooks = append(srUpdatedEwDatabaseLinkVersionAfterSelectHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.AfterUpdateHook:
		srUpdatedEwDatabaseLinkVersionAfterUpdateHooks = append(srUpdatedEwDatabaseLinkVersionAfterUpdateHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.AfterDeleteHook:
		srUpdatedEwDatabaseLinkVersionAfterDeleteHooks = append(srUpdatedEwDatabaseLinkVersionAfterDeleteHooks, srUpdatedEwDatabaseLinkVersionHook)
	case boil.AfterUpsertHook:
		srUpdatedEwDatabaseLinkVersionAfterUpsertHooks = append(srUpdatedEwDatabaseLinkVersionAfterUpsertHooks, srUpdatedEwDatabaseLinkVersionHook)
	}
}

// OneP returns a single srUpdatedEwDatabaseLinkVersion record from the query, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) OneP() *SRUpdatedEwDatabaseLinkVersion {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single srUpdatedEwDatabaseLinkVersion record from the query.
func (q srUpdatedEwDatabaseLinkVersionQuery) One() (*SRUpdatedEwDatabaseLinkVersion, error) {
	o := &SRUpdatedEwDatabaseLinkVersion{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for sr_updated_ew_database_link_versions")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all SRUpdatedEwDatabaseLinkVersion records from the query, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) AllP() SRUpdatedEwDatabaseLinkVersionSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all SRUpdatedEwDatabaseLinkVersion records from the query.
func (q srUpdatedEwDatabaseLinkVersionQuery) All() (SRUpdatedEwDatabaseLinkVersionSlice, error) {
	var o []*SRUpdatedEwDatabaseLinkVersion

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to SRUpdatedEwDatabaseLinkVersion slice")
	}

	if len(srUpdatedEwDatabaseLinkVersionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all SRUpdatedEwDatabaseLinkVersion records in the query, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all SRUpdatedEwDatabaseLinkVersion records in the query.
func (q srUpdatedEwDatabaseLinkVersionQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count sr_updated_ew_database_link_versions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q srUpdatedEwDatabaseLinkVersionQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if sr_updated_ew_database_link_versions exists")
	}

	return count > 0, nil
}

// SRG pointed to by the foreign key.
func (o *SRUpdatedEwDatabaseLinkVersion) SRG(mods ...qm.QueryMod) synchronizationRaportQuery {
	return o.SR(boil.GetDB(), mods...)
}

// SR pointed to by the foreign key.
func (o *SRUpdatedEwDatabaseLinkVersion) SR(exec boil.Executor, mods ...qm.QueryMod) synchronizationRaportQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.SRID),
	}

	queryMods = append(queryMods, mods...)

	query := SynchronizationRaports(exec, queryMods...)
	queries.SetFrom(query.Query, "`synchronization_raports`")

	return query
}

// VariationG pointed to by the foreign key.
func (o *SRUpdatedEwDatabaseLinkVersion) VariationG(mods ...qm.QueryMod) variationQuery {
	return o.Variation(boil.GetDB(), mods...)
}

// Variation pointed to by the foreign key.
func (o *SRUpdatedEwDatabaseLinkVersion) Variation(exec boil.Executor, mods ...qm.QueryMod) variationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.VariationID),
	}

	queryMods = append(queryMods, mods...)

	query := Variations(exec, queryMods...)
	queries.SetFrom(query.Query, "`variations`")

	return query
} // LoadSR allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (srUpdatedEwDatabaseLinkVersionL) LoadSR(e boil.Executor, singular bool, maybeSRUpdatedEwDatabaseLinkVersion interface{}) error {
	var slice []*SRUpdatedEwDatabaseLinkVersion
	var object *SRUpdatedEwDatabaseLinkVersion

	count := 1
	if singular {
		object = maybeSRUpdatedEwDatabaseLinkVersion.(*SRUpdatedEwDatabaseLinkVersion)
	} else {
		slice = *maybeSRUpdatedEwDatabaseLinkVersion.(*[]*SRUpdatedEwDatabaseLinkVersion)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &srUpdatedEwDatabaseLinkVersionR{}
		}
		args[0] = object.SRID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &srUpdatedEwDatabaseLinkVersionR{}
			}
			args[i] = obj.SRID
		}
	}

	query := fmt.Sprintf(
		"select * from `synchronization_raports` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load SynchronizationRaport")
	}
	defer results.Close()

	var resultSlice []*SynchronizationRaport
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice SynchronizationRaport")
	}

	if len(srUpdatedEwDatabaseLinkVersionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.SR = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SRID == foreign.ID {
				local.R.SR = foreign
				break
			}
		}
	}

	return nil
}

// LoadVariation allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (srUpdatedEwDatabaseLinkVersionL) LoadVariation(e boil.Executor, singular bool, maybeSRUpdatedEwDatabaseLinkVersion interface{}) error {
	var slice []*SRUpdatedEwDatabaseLinkVersion
	var object *SRUpdatedEwDatabaseLinkVersion

	count := 1
	if singular {
		object = maybeSRUpdatedEwDatabaseLinkVersion.(*SRUpdatedEwDatabaseLinkVersion)
	} else {
		slice = *maybeSRUpdatedEwDatabaseLinkVersion.(*[]*SRUpdatedEwDatabaseLinkVersion)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &srUpdatedEwDatabaseLinkVersionR{}
		}
		args[0] = object.VariationID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &srUpdatedEwDatabaseLinkVersionR{}
			}
			args[i] = obj.VariationID
		}
	}

	query := fmt.Sprintf(
		"select * from `variations` where `id` in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Variation")
	}
	defer results.Close()

	var resultSlice []*Variation
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Variation")
	}

	if len(srUpdatedEwDatabaseLinkVersionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Variation = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.VariationID == foreign.ID {
				local.R.Variation = foreign
				break
			}
		}
	}

	return nil
}

// SetSRG of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.SR to related.
// Adds o to related.R.SRSRUpdatedEwDatabaseLinkVersions.
// Uses the global database handle.
func (o *SRUpdatedEwDatabaseLinkVersion) SetSRG(insert bool, related *SynchronizationRaport) error {
	return o.SetSR(boil.GetDB(), insert, related)
}

// SetSRP of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.SR to related.
// Adds o to related.R.SRSRUpdatedEwDatabaseLinkVersions.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) SetSRP(exec boil.Executor, insert bool, related *SynchronizationRaport) {
	if err := o.SetSR(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSRGP of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.SR to related.
// Adds o to related.R.SRSRUpdatedEwDatabaseLinkVersions.
// Uses the global database handle and panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) SetSRGP(insert bool, related *SynchronizationRaport) {
	if err := o.SetSR(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSR of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.SR to related.
// Adds o to related.R.SRSRUpdatedEwDatabaseLinkVersions.
func (o *SRUpdatedEwDatabaseLinkVersion) SetSR(exec boil.Executor, insert bool, related *SynchronizationRaport) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sr_updated_ew_database_link_versions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"sr_id"}),
		strmangle.WhereClause("`", "`", 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SRID = related.ID

	if o.R == nil {
		o.R = &srUpdatedEwDatabaseLinkVersionR{
			SR: related,
		}
	} else {
		o.R.SR = related
	}

	if related.R == nil {
		related.R = &synchronizationRaportR{
			SRSRUpdatedEwDatabaseLinkVersions: SRUpdatedEwDatabaseLinkVersionSlice{o},
		}
	} else {
		related.R.SRSRUpdatedEwDatabaseLinkVersions = append(related.R.SRSRUpdatedEwDatabaseLinkVersions, o)
	}

	return nil
}

// SetVariationG of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.Variation to related.
// Adds o to related.R.SRUpdatedEwDatabaseLinkVersions.
// Uses the global database handle.
func (o *SRUpdatedEwDatabaseLinkVersion) SetVariationG(insert bool, related *Variation) error {
	return o.SetVariation(boil.GetDB(), insert, related)
}

// SetVariationP of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.Variation to related.
// Adds o to related.R.SRUpdatedEwDatabaseLinkVersions.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) SetVariationP(exec boil.Executor, insert bool, related *Variation) {
	if err := o.SetVariation(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetVariationGP of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.Variation to related.
// Adds o to related.R.SRUpdatedEwDatabaseLinkVersions.
// Uses the global database handle and panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) SetVariationGP(insert bool, related *Variation) {
	if err := o.SetVariation(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetVariation of the sr_updated_ew_database_link_version to the related item.
// Sets o.R.Variation to related.
// Adds o to related.R.SRUpdatedEwDatabaseLinkVersions.
func (o *SRUpdatedEwDatabaseLinkVersion) SetVariation(exec boil.Executor, insert bool, related *Variation) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `sr_updated_ew_database_link_versions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"variation_id"}),
		strmangle.WhereClause("`", "`", 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.VariationID = related.ID

	if o.R == nil {
		o.R = &srUpdatedEwDatabaseLinkVersionR{
			Variation: related,
		}
	} else {
		o.R.Variation = related
	}

	if related.R == nil {
		related.R = &variationR{
			SRUpdatedEwDatabaseLinkVersions: SRUpdatedEwDatabaseLinkVersionSlice{o},
		}
	} else {
		related.R.SRUpdatedEwDatabaseLinkVersions = append(related.R.SRUpdatedEwDatabaseLinkVersions, o)
	}

	return nil
}

// SRUpdatedEwDatabaseLinkVersionsG retrieves all records.
func SRUpdatedEwDatabaseLinkVersionsG(mods ...qm.QueryMod) srUpdatedEwDatabaseLinkVersionQuery {
	return SRUpdatedEwDatabaseLinkVersions(boil.GetDB(), mods...)
}

// SRUpdatedEwDatabaseLinkVersions retrieves all the records using an executor.
func SRUpdatedEwDatabaseLinkVersions(exec boil.Executor, mods ...qm.QueryMod) srUpdatedEwDatabaseLinkVersionQuery {
	mods = append(mods, qm.From("`sr_updated_ew_database_link_versions`"))
	return srUpdatedEwDatabaseLinkVersionQuery{NewQuery(exec, mods...)}
}

// FindSRUpdatedEwDatabaseLinkVersionG retrieves a single record by ID.
func FindSRUpdatedEwDatabaseLinkVersionG(id uint64, selectCols ...string) (*SRUpdatedEwDatabaseLinkVersion, error) {
	return FindSRUpdatedEwDatabaseLinkVersion(boil.GetDB(), id, selectCols...)
}

// FindSRUpdatedEwDatabaseLinkVersionGP retrieves a single record by ID, and panics on error.
func FindSRUpdatedEwDatabaseLinkVersionGP(id uint64, selectCols ...string) *SRUpdatedEwDatabaseLinkVersion {
	retobj, err := FindSRUpdatedEwDatabaseLinkVersion(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSRUpdatedEwDatabaseLinkVersion retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSRUpdatedEwDatabaseLinkVersion(exec boil.Executor, id uint64, selectCols ...string) (*SRUpdatedEwDatabaseLinkVersion, error) {
	srUpdatedEwDatabaseLinkVersionObj := &SRUpdatedEwDatabaseLinkVersion{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `sr_updated_ew_database_link_versions` where `id`=?", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(srUpdatedEwDatabaseLinkVersionObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from sr_updated_ew_database_link_versions")
	}

	return srUpdatedEwDatabaseLinkVersionObj, nil
}

// FindSRUpdatedEwDatabaseLinkVersionP retrieves a single record by ID with an executor, and panics on error.
func FindSRUpdatedEwDatabaseLinkVersionP(exec boil.Executor, id uint64, selectCols ...string) *SRUpdatedEwDatabaseLinkVersion {
	retobj, err := FindSRUpdatedEwDatabaseLinkVersion(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *SRUpdatedEwDatabaseLinkVersion) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no sr_updated_ew_database_link_versions provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(srUpdatedEwDatabaseLinkVersionColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	srUpdatedEwDatabaseLinkVersionInsertCacheMut.RLock()
	cache, cached := srUpdatedEwDatabaseLinkVersionInsertCache[key]
	srUpdatedEwDatabaseLinkVersionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			srUpdatedEwDatabaseLinkVersionColumns,
			srUpdatedEwDatabaseLinkVersionColumnsWithDefault,
			srUpdatedEwDatabaseLinkVersionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `sr_updated_ew_database_link_versions` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `sr_updated_ew_database_link_versions` () VALUES ()"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `sr_updated_ew_database_link_versions` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into sr_updated_ew_database_link_versions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == srUpdatedEwDatabaseLinkVersionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sr_updated_ew_database_link_versions")
	}

CacheNoHooks:
	if !cached {
		srUpdatedEwDatabaseLinkVersionInsertCacheMut.Lock()
		srUpdatedEwDatabaseLinkVersionInsertCache[key] = cache
		srUpdatedEwDatabaseLinkVersionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single SRUpdatedEwDatabaseLinkVersion record. See Update for
// whitelist behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single SRUpdatedEwDatabaseLinkVersion record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the SRUpdatedEwDatabaseLinkVersion, and panics on error.
// See Update for whitelist behavior description.
func (o *SRUpdatedEwDatabaseLinkVersion) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the SRUpdatedEwDatabaseLinkVersion.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *SRUpdatedEwDatabaseLinkVersion) Update(exec boil.Executor, whitelist ...string) error {
	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	srUpdatedEwDatabaseLinkVersionUpdateCacheMut.RLock()
	cache, cached := srUpdatedEwDatabaseLinkVersionUpdateCache[key]
	srUpdatedEwDatabaseLinkVersionUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			srUpdatedEwDatabaseLinkVersionColumns,
			srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update sr_updated_ew_database_link_versions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `sr_updated_ew_database_link_versions` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, append(wl, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update sr_updated_ew_database_link_versions row")
	}

	if !cached {
		srUpdatedEwDatabaseLinkVersionUpdateCacheMut.Lock()
		srUpdatedEwDatabaseLinkVersionUpdateCache[key] = cache
		srUpdatedEwDatabaseLinkVersionUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q srUpdatedEwDatabaseLinkVersionQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for sr_updated_ew_database_link_versions")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SRUpdatedEwDatabaseLinkVersionSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o SRUpdatedEwDatabaseLinkVersionSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o SRUpdatedEwDatabaseLinkVersionSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SRUpdatedEwDatabaseLinkVersionSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), srUpdatedEwDatabaseLinkVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `sr_updated_ew_database_link_versions` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in srUpdatedEwDatabaseLinkVersion slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *SRUpdatedEwDatabaseLinkVersion) UpsertG(updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) UpsertGP(updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) UpsertP(exec boil.Executor, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *SRUpdatedEwDatabaseLinkVersion) Upsert(exec boil.Executor, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no sr_updated_ew_database_link_versions provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(srUpdatedEwDatabaseLinkVersionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	srUpdatedEwDatabaseLinkVersionUpsertCacheMut.RLock()
	cache, cached := srUpdatedEwDatabaseLinkVersionUpsertCache[key]
	srUpdatedEwDatabaseLinkVersionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			srUpdatedEwDatabaseLinkVersionColumns,
			srUpdatedEwDatabaseLinkVersionColumnsWithDefault,
			srUpdatedEwDatabaseLinkVersionColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			srUpdatedEwDatabaseLinkVersionColumns,
			srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert sr_updated_ew_database_link_versions, could not build update column list")
		}

		cache.query = queries.BuildUpsertQueryMySQL(dialect, "sr_updated_ew_database_link_versions", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `sr_updated_ew_database_link_versions` WHERE `id`=?",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
		)

		cache.valueMapping, err = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(srUpdatedEwDatabaseLinkVersionType, srUpdatedEwDatabaseLinkVersionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	result, err := exec.Exec(cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for sr_updated_ew_database_link_versions")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = uint64(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == srUpdatedEwDatabaseLinkVersionMapping["ID"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.retQuery)
		fmt.Fprintln(boil.DebugWriter, identifierCols...)
	}

	err = exec.QueryRow(cache.retQuery, identifierCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for sr_updated_ew_database_link_versions")
	}

CacheNoHooks:
	if !cached {
		srUpdatedEwDatabaseLinkVersionUpsertCacheMut.Lock()
		srUpdatedEwDatabaseLinkVersionUpsertCache[key] = cache
		srUpdatedEwDatabaseLinkVersionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single SRUpdatedEwDatabaseLinkVersion record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single SRUpdatedEwDatabaseLinkVersion record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *SRUpdatedEwDatabaseLinkVersion) DeleteG() error {
	if o == nil {
		return errors.New("models: no SRUpdatedEwDatabaseLinkVersion provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single SRUpdatedEwDatabaseLinkVersion record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single SRUpdatedEwDatabaseLinkVersion record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SRUpdatedEwDatabaseLinkVersion) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no SRUpdatedEwDatabaseLinkVersion provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), srUpdatedEwDatabaseLinkVersionPrimaryKeyMapping)
	sql := "DELETE FROM `sr_updated_ew_database_link_versions` WHERE `id`=?"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from sr_updated_ew_database_link_versions")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q srUpdatedEwDatabaseLinkVersionQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q srUpdatedEwDatabaseLinkVersionQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no srUpdatedEwDatabaseLinkVersionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from sr_updated_ew_database_link_versions")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o SRUpdatedEwDatabaseLinkVersionSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o SRUpdatedEwDatabaseLinkVersionSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no SRUpdatedEwDatabaseLinkVersion slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o SRUpdatedEwDatabaseLinkVersionSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SRUpdatedEwDatabaseLinkVersionSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no SRUpdatedEwDatabaseLinkVersion slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(srUpdatedEwDatabaseLinkVersionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), srUpdatedEwDatabaseLinkVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `sr_updated_ew_database_link_versions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from srUpdatedEwDatabaseLinkVersion slice")
	}

	if len(srUpdatedEwDatabaseLinkVersionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersion) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *SRUpdatedEwDatabaseLinkVersion) ReloadG() error {
	if o == nil {
		return errors.New("models: no SRUpdatedEwDatabaseLinkVersion provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SRUpdatedEwDatabaseLinkVersion) Reload(exec boil.Executor) error {
	ret, err := FindSRUpdatedEwDatabaseLinkVersion(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersionSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SRUpdatedEwDatabaseLinkVersionSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SRUpdatedEwDatabaseLinkVersionSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty SRUpdatedEwDatabaseLinkVersionSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SRUpdatedEwDatabaseLinkVersionSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	srUpdatedEwDatabaseLinkVersions := SRUpdatedEwDatabaseLinkVersionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), srUpdatedEwDatabaseLinkVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `sr_updated_ew_database_link_versions`.* FROM `sr_updated_ew_database_link_versions` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, srUpdatedEwDatabaseLinkVersionPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&srUpdatedEwDatabaseLinkVersions)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SRUpdatedEwDatabaseLinkVersionSlice")
	}

	*o = srUpdatedEwDatabaseLinkVersions

	return nil
}

// SRUpdatedEwDatabaseLinkVersionExists checks if the SRUpdatedEwDatabaseLinkVersion row exists.
func SRUpdatedEwDatabaseLinkVersionExists(exec boil.Executor, id uint64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `sr_updated_ew_database_link_versions` where `id`=? limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if sr_updated_ew_database_link_versions exists")
	}

	return exists, nil
}

// SRUpdatedEwDatabaseLinkVersionExistsG checks if the SRUpdatedEwDatabaseLinkVersion row exists.
func SRUpdatedEwDatabaseLinkVersionExistsG(id uint64) (bool, error) {
	return SRUpdatedEwDatabaseLinkVersionExists(boil.GetDB(), id)
}

// SRUpdatedEwDatabaseLinkVersionExistsGP checks if the SRUpdatedEwDatabaseLinkVersion row exists. Panics on error.
func SRUpdatedEwDatabaseLinkVersionExistsGP(id uint64) bool {
	e, err := SRUpdatedEwDatabaseLinkVersionExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SRUpdatedEwDatabaseLinkVersionExistsP checks if the SRUpdatedEwDatabaseLinkVersion row exists. Panics on error.
func SRUpdatedEwDatabaseLinkVersionExistsP(exec boil.Executor, id uint64) bool {
	e, err := SRUpdatedEwDatabaseLinkVersionExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
